Repository arco-design/arco-design-vue, pull requests merged in 2021-12, with the labels that each got.

#287 feat(font): add body font-family
  packages/web-vue/components/style/index.less
Labels: 🔮 style

#293 feat(input-number): add size props
  packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/TEMPLATE.md
  packages/web-vue/components/input-number/__demo__/size.md
  packages/web-vue/components/input-number/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/pagination/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/slider/__test__/__snapshots__/demo.test.ts.snap
Labels: 🐞 bug

#296 fix(list): add empty status
  packages/web-vue/components/list/__test__/index.test.ts
  packages/web-vue/components/list/list.tsx
Labels: ✨ enhancement

#297 fix: Fix drawer popup container not work & fix[Pagination]: disable jumper and pageSize selector when disabled is true
  packages/web-vue/components/comment/style/index.less
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/TEMPLATE.md
  packages/web-vue/components/drawer/__demo__/popup-container.md
  packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/drawer/style/index.less
  packages/web-vue/components/drawer/style/token.less
  packages/web-vue/components/dropdown/style/index.less
  packages/web-vue/components/dropdown/style/token.less
  packages/web-vue/components/empty/style/index.less
  packages/web-vue/components/empty/style/token.less
  packages/web-vue/components/list/style/index.less
  packages/web-vue/components/page-header/page-header.vue
  packages/web-vue/components/page-header/style/index.less
  packages/web-vue/components/page-header/style/token.less
  packages/web-vue/components/pagination/page-jumper.vue
  packages/web-vue/components/pagination/page-options.vue
  packages/web-vue/components/pagination/pagination.tsx
  packages/web-vue/components/pagination/style/index.less
Labels: 🐞 bug

#305 fix: Progress slots text not work
  packages/web-vue/components/progress/README.en-US.md
  packages/web-vue/components/progress/README.zh-CN.md
  packages/web-vue/components/progress/TEMPLATE.md
  packages/web-vue/components/progress/__demo__/basic.md
  packages/web-vue/components/progress/__demo__/circle.md
  packages/web-vue/components/progress/__demo__/linear.md
  packages/web-vue/components/progress/__demo__/mini.md
  packages/web-vue/components/progress/__demo__/steps.md
  packages/web-vue/components/progress/__demo__/trackColor.md
  packages/web-vue/components/progress/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/progress/circle.vue
  packages/web-vue/components/progress/progress.vue
  packages/web-vue/components/progress/style/index.less
  packages/web-vue/components/progress/style/token.less
  packages/web-vue/components/radio/style/index.less
  packages/web-vue/components/radio/style/token.less
  packages/web-vue/components/spin/dot-loading.tsx
  packages/web-vue/components/spin/style/dot-loading.less
  packages/web-vue/components/spin/style/token.less
  packages/web-vue/components/statistic/style/index.less
  packages/web-vue/components/statistic/style/token.less
Labels: 🐞 bug

#302 feat: result supports extra slot and content slots
  packages/web-vue/components/result/README.en-US.md
  packages/web-vue/components/result/README.zh-CN.md
  packages/web-vue/components/result/TEMPLATE.md
  packages/web-vue/components/result/__demo__/403.md
  packages/web-vue/components/result/__demo__/404.md
  packages/web-vue/components/result/__demo__/500.md
  packages/web-vue/components/result/__demo__/all.md
  packages/web-vue/components/result/__demo__/basic.md
  packages/web-vue/components/result/__demo__/custom.md
  packages/web-vue/components/result/__demo__/error.md
  packages/web-vue/components/result/__demo__/success.md
  packages/web-vue/components/result/__demo__/warning.md
  packages/web-vue/components/result/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/result/result.vue
  packages/web-vue/components/result/style/index.less
  packages/web-vue/components/result/style/token.less
Labels: ✨ enhancement, feature

#311 fix: some bugs fix and perf
  packages/web-vue/components/_utils/vue-utils.ts
  packages/web-vue/components/form/form-item.tsx
  packages/web-vue/components/space/space.tsx
  packages/web-vue/components/spin/spin.tsx
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#310 fix(auto-complete): fix disabled problem
  packages/web-vue/components/auto-complete/auto-complete.tsx
Labels: 🐞 bug

#309 feat(textarea): support min & max rows
  packages/web-vue/components/_utils/constant.ts
  packages/web-vue/components/textarea/__demo__/auto-size.md
  packages/web-vue/components/textarea/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/textarea/textarea.vue
  packages/web-vue/components/textarea/utils.ts
Labels: ✨ enhancement

#308 fix: remove radio & cascader selected font-weight
  packages/web-vue/components/cascader/style/index.less
  packages/web-vue/components/radio/style/index.less
Labels: 🔮 style

#307 feat: add tag-props support
  packages/web-vue/.eslintrc.js
  packages/web-vue/components/_components/dropdown/dropdown-option.vue
  packages/web-vue/components/_components/dropdown/utils.ts
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/__demo__/multiple.md
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/interface.ts
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input-tag/interface.ts
  packages/web-vue/components/input-tag/utils.ts
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/utils.ts
  packages/web-vue/components/tag/index.ts
Labels: ✨ enhancement

#306 feat(menu): add prop auto-open-selected
  packages/web-vue/components/menu/README.en-US.md
  packages/web-vue/components/menu/README.zh-CN.md
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/menu/context.ts
  packages/web-vue/components/menu/hooks/use-level.ts
  packages/web-vue/components/menu/hooks/use-menu-context.ts
  packages/web-vue/components/menu/hooks/use-menu-data-collector.ts
  packages/web-vue/components/menu/hooks/use-menu-open-state.ts
  packages/web-vue/components/menu/interface.ts
  packages/web-vue/components/menu/item.tsx
  packages/web-vue/components/menu/menu.tsx
Labels: feature

#206 fix(tree): execute onCheck function after load more
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/tree.vue
Labels: 🐞 bug

#318 fix: fix render comment item
  packages/web-vue/components/space/space.tsx
Labels: 🐞 bug

#316 feat(steps): add title props
  packages/web-vue/components/steps/README.en-US.md
  packages/web-vue/components/steps/README.zh-CN.md
  packages/web-vue/components/steps/step.vue
Labels: ✨ enhancement

#325 feat: drawer supports okButtonProps & cancelButtonProps
  packages/web-vue/components/drawer/drawer.vue
Labels: feature

#324 feat(pagination): add slot & formatTotal
  packages/web-vue/components/pagination/README.en-US.md
  packages/web-vue/components/pagination/README.zh-CN.md
  packages/web-vue/components/pagination/TEMPLATE.md
  packages/web-vue/components/pagination/__demo__/custom.md
  packages/web-vue/components/pagination/page-item-ellipsis.vue
  packages/web-vue/components/pagination/page-item-step.vue
  packages/web-vue/components/pagination/page-item.vue
  packages/web-vue/components/pagination/pagination.tsx
  packages/web-vue/components/pagination/style/index.less
  packages/web-vue/components/table/table.tsx
Labels: ✨ enhancement

#321 fix: fix button trigger form submit
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#323 feat(script): support generate version
  packages/arco-vue-docs/components/article/style.less
  packages/arco-vue-scripts/src/scripts/docgen/templates/events.ts
  packages/arco-vue-scripts/src/scripts/docgen/templates/methods.ts
  packages/arco-vue-scripts/src/scripts/docgen/templates/props.ts
  packages/arco-vue-scripts/src/scripts/docgen/templates/slots.ts
Labels: feature

#322 feat(tree): add prop default-expand-selected default-expand-checked auto-expand-parent
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
Labels: feature

#320 fix: fix remount problem
  packages/web-vue/components/spin/spin.tsx
Labels: 🐞 bug

#343 fix(carousel): carousel item cover
  packages/web-vue/components/carousel/style/index.less
Labels: 🐞 bug

#345 chore(input-tag): optimize animation & style
  packages/web-vue/components/input-tag/__demo__/status.md
  packages/web-vue/components/input-tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input-tag/style/index.less
  packages/web-vue/components/input-tag/style/input-tag.less
  packages/web-vue/components/input-tag/utils.ts
  packages/web-vue/components/input/style/input.less
  packages/web-vue/components/tag/style/index.less
Labels: 🔮 style

#340 feat(grid): add flex property
  packages/web-vue/components/grid/README.en-US.md
  packages/web-vue/components/grid/README.zh-CN.md
  packages/web-vue/components/grid/TEMPLATE.md
  packages/web-vue/components/grid/__demo__/flex.md
  packages/web-vue/components/grid/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/grid/context.ts
  packages/web-vue/components/grid/grid-col.vue
  packages/web-vue/components/grid/grid-row.tsx
  packages/web-vue/components/grid/grid-row.vue
  packages/web-vue/components/grid/index.ts
  packages/web-vue/components/grid/interface.ts
Labels: feature

#346 fix(menu): fix the problem that the width of the menu cannot fill the parent element
  packages/web-vue/components/menu/style/index.less
Labels: 🔮 style

#350 feat(dropdown): add footer slot
  packages/arco-vue-scripts/src/scripts/docgen/templates/slots.ts
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/TEMPLATE.md
  packages/web-vue/components/dropdown/__demo__/icon.md
  packages/web-vue/components/dropdown/context.ts
  packages/web-vue/components/dropdown/dropdown-group.ts
  packages/web-vue/components/dropdown/dropdown-group.vue
  packages/web-vue/components/dropdown/dropdown-option.ts
  packages/web-vue/components/dropdown/dropdown-option.vue
  packages/web-vue/components/dropdown/dropdown-submenu.ts
  packages/web-vue/components/dropdown/dropdown-submenu.vue
  packages/web-vue/components/dropdown/dropdown.tsx
  packages/web-vue/components/dropdown/dropdown.vue
  packages/web-vue/components/dropdown/index.ts
  packages/web-vue/components/dropdown/interface.ts
  packages/web-vue/components/dropdown/style/index.ts
  packages/web-vue/components/dropdown/utils.ts
  packages/web-vue/components/pagination/README.en-US.md
  packages/web-vue/components/pagination/README.zh-CN.md
  packages/web-vue/components/result/README.en-US.md
  packages/web-vue/components/result/README.zh-CN.md
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
Labels: ✨ enhancement

#351 fix(modal): fix modal message style error
  packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/modal/index.tsx
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/modal/style/index.less
Labels: 🔮 style

#354 fix(message): update message style
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/_components/select-view/style/index.less
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/message/style/index.less
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/__demo__/linkage.md
  packages/web-vue/components/select/base-select.tsx
Labels: 🔮 style

#355 fix(textarea): fix disabled style
  packages/web-vue/components/textarea/__demo__/status.md
  packages/web-vue/components/textarea/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/textarea/textarea.vue
Labels: 🔮 style

#356 fix(tabs): fix closable problem
  packages/web-vue/components/tabs/tabs-tab.vue
Labels: 🐞 bug

#357 fix(statistic): fix precision problem
  packages/web-vue/components/statistic/README.en-US.md
  packages/web-vue/components/statistic/README.zh-CN.md
  packages/web-vue/components/statistic/statistic.vue
Labels: 🐞 bug

#358 feat(collapse): key add number support
  packages/web-vue/components/collapse/README.en-US.md
  packages/web-vue/components/collapse/README.zh-CN.md
  packages/web-vue/components/collapse/__demo__/basic.md
  packages/web-vue/components/collapse/collapse-item.vue
  packages/web-vue/components/collapse/collapse.vue
  packages/web-vue/components/collapse/context.ts
Labels: ✨ enhancement

#359 fix(input-number): fix input - & . problem
  packages/web-vue/components/input-number/__demo__/basic.md
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input/input.tsx
Labels: 🐞 bug

#361 feat(form): add some props
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/form-item.tsx
Labels: ✨ enhancement

#362 feat(tabs): add headerPadding
  packages/web-vue/components/tabs/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tabs/style/index.less
  packages/web-vue/components/tabs/tabs-nav.tsx
  packages/web-vue/components/tabs/tabs.tsx
Labels: ✨ enhancement

#372 docs: update some changelog docs
  packages/web-vue/components/avatar/CHANGELOG.zh-CN.md
  packages/web-vue/components/carousel/CHANGELOG.zh-CN.md
  packages/web-vue/components/input-tag/CHANGELOG.zh-CN.md
  packages/web-vue/components/steps/CHANGELOG.zh-CN.md
Labels: 📖 documentation

#380 fix(card): refactor card, fix slots problem
  packages/web-vue/components/card/__demo__/bordered.md
  packages/web-vue/components/card/card-meta.tsx
  packages/web-vue/components/card/card.tsx
  packages/web-vue/components/card/context.ts
Labels: 🐞 bug

#382 fix(trigger): fix popup resize & alignPoint problem
  packages/web-vue/components/trigger/trigger.tsx
Labels: 🐞 bug

#383 fix(input): fix input & input-tag style problem
  packages/web-vue/components/input-tag/style/input-tag.less
  packages/web-vue/components/input/style/input.less
Labels: 🔮 style

#385 fix(dropdown): fix attrs & props inherit problem
  packages/web-vue/components/_components/input-label/input-label.tsx
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/_components/select-view/style/index.less
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/__demo__/submenu.md
  packages/web-vue/components/dropdown/dropdown-submenu.ts
  packages/web-vue/components/dropdown/dropdown.tsx
  packages/web-vue/components/dropdown/interface.ts
  packages/web-vue/components/dropdown/utils.ts
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/TEMPLATE.md
  packages/web-vue/components/select/__demo__/border.md
  packages/web-vue/components/select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/base-select.tsx
Labels: 🐞 bug

#388 fix(cascader): fix totalLeafOptions cal
  packages/web-vue/components/cascader/utils.ts
Labels: 🐞 bug

#390 fix(popconfirm): fix style problem
  packages/web-vue/components/popconfirm/README.en-US.md
  packages/web-vue/components/popconfirm/README.zh-CN.md
  packages/web-vue/components/popconfirm/popconfirm.vue
  packages/web-vue/components/popconfirm/style/index.less
  packages/web-vue/components/popconfirm/style/token.less
Labels: 🔮 style

#394 feat(Drawer): add show-footer Props
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/drawer.vue
Labels: ✨ feature

#399 fix(cascader): fix totalLevel error
  packages/web-vue/components/cascader/utils.ts
Labels: 🐞 bug

#384 fix: the align-center property of Modal not work
  packages/web-vue/components/anchor/style/index.less
  packages/web-vue/components/breadcrumb/style/index.less
  packages/web-vue/components/breadcrumb/style/token.less
  packages/web-vue/components/message/style/index.less
  packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/modal/style/index.less
Labels: 🐞 bug

#405 fix(tree-select): fix the problem that filter is invalid when rename the key field
  packages/web-vue/components/tree-select/__demo__/basic.md
  packages/web-vue/components/tree-select/__demo__/checkable.md
  packages/web-vue/components/tree-select/__demo__/checked-strategy.md
  packages/web-vue/components/tree-select/__demo__/control.md
  packages/web-vue/components/tree-select/__demo__/field-names.md
  packages/web-vue/components/tree-select/__demo__/label-in-value.md
  packages/web-vue/components/tree-select/__demo__/load-more.md
  packages/web-vue/components/tree-select/__demo__/multiple.md
  packages/web-vue/components/tree-select/__demo__/popup-visible.md
  packages/web-vue/components/tree-select/__demo__/search-remote.md
  packages/web-vue/components/tree-select/__demo__/search.md
  packages/web-vue/components/tree-select/__demo__/size.md
  packages/web-vue/components/tree-select/__demo__/virtual.md
  packages/web-vue/components/tree-select/hooks/use-filter-tree-node.ts
  packages/web-vue/components/tree-select/tree-select.vue
Labels: 🐞 bug

#400 fix(anchor): fix positioning during initialization problem
  packages/web-vue/components/_utils/dom.ts
  packages/web-vue/components/anchor/anchor.vue
  packages/web-vue/components/anchor/context.ts
  packages/web-vue/components/anchor/utils.ts
Labels: 🐞 bug

#415 feat(space): add fill property
  packages/web-vue/components/space/README.en-US.md
  packages/web-vue/components/space/README.zh-CN.md
  packages/web-vue/components/space/__demo__/vertical.md
  packages/web-vue/components/space/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/space/space.tsx
  packages/web-vue/components/space/style/index.less
Labels: ✨ feature

#416 fix(layout): the sider overflows when collapse is true
  packages/web-vue/components/layout/style/index.less
Labels: 🔮 style

#412 feat(menu): add icon slot
  packages/web-vue/components/menu/README.en-US.md
  packages/web-vue/components/menu/README.zh-CN.md
  packages/web-vue/components/menu/__demo__/collapse-control.md
  packages/web-vue/components/menu/__demo__/pop-button.md
  packages/web-vue/components/menu/__demo__/pop.md
  packages/web-vue/components/menu/__demo__/size.md
  packages/web-vue/components/menu/__demo__/sub-menu.md
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/interface.ts
  packages/web-vue/components/menu/item.tsx
  packages/web-vue/components/menu/style/index.less
  packages/web-vue/components/menu/sub-menu-inline.vue
  packages/web-vue/components/menu/sub-menu-pop.vue
  packages/web-vue/components/menu/sub-menu.tsx
Labels: ✨ feature

#406 fix(trigger): fix resize & context problem
  packages/web-vue/components/_hooks/use-resize-observer.ts
  packages/web-vue/components/trigger/context.ts
  packages/web-vue/components/trigger/trigger.tsx
Labels: 🐞 bug

#407 fix(input-number): fix model-value display problem
  packages/web-vue/components/input-number/input-number.tsx
Labels: 🐞 bug

#408 fix(input-tag): fix mirror resize problem
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: 🐞 bug

#409 fix(tabs): fix ink resize problem
  packages/web-vue/components/tabs/tabs-nav-ink.vue
  packages/web-vue/components/tabs/tabs-nav.tsx
Labels: 🐞 bug

#410 fix(table): fix fixed table resize
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#411 feat(table): add cellStyle
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
Labels: ✨ feature

#414 fix(drawer): fix close btn style
  packages/web-vue/components/drawer/style/index.less
  packages/web-vue/components/modal/style/index.less
Labels: 🔮 style

#396 feat(upload): add props
  packages/web-vue/CHANGELOG.md
  packages/web-vue/CHANGELOG.zh-CN.md
  packages/web-vue/components/upload/context.ts
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload-list.tsx
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload-progress.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: ✨ feature

#418 feat(upload): add download prop
  packages/web-vue/CHANGELOG.md
  packages/web-vue/CHANGELOG.zh-CN.md
  packages/web-vue/components/upload/context.ts
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload-list.tsx
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload-progress.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: ✨ feature

#427 fix(dropdown): fix JSX render problem
  packages/web-vue-storybook/stories/components/dropdown.tsx
  packages/web-vue-storybook/stories/index.stories.ts
  packages/web-vue/components/dropdown/utils.ts
  packages/web-vue/components/select/utils.ts
Labels: 🐞 bug

#428 fix(input-tag): fix input problem
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: 🐞 bug

#448 fix(resize): fix nest problem
  packages/web-vue/components/_components/resize-observer.tsx
Labels: 🐞 bug

#451 feat(input): add errorOnly and word-slice
  packages/web-vue/components/input/README.en-US.md
  packages/web-vue/components/input/README.zh-CN.md
  packages/web-vue/components/input/__demo__/word-limit.md
  packages/web-vue/components/input/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/input/style/index.less
  packages/web-vue/components/textarea/README.en-US.md
  packages/web-vue/components/textarea/README.zh-CN.md
  packages/web-vue/components/textarea/__demo__/word-limit.md
  packages/web-vue/components/textarea/textarea.vue
Labels: ✨ feature

#450 feat(link): add click event
  packages/web-vue/components/link/link.vue
Labels: ✨ feature

#447 fix(progress): fix precision problem
  packages/web-vue/components/progress/circle.vue
  packages/web-vue/components/progress/line.vue
  packages/web-vue/components/progress/steps.vue
Labels: 🐞 bug

#446 fix(upload): render tip on basic type
  packages/web-vue/components/upload/upload-button.tsx
Labels: 🐞 bug

#444 feat(switch): add custom value & color
  packages/web-vue/components/switch/README.en-US.md
  packages/web-vue/components/switch/README.zh-CN.md
  packages/web-vue/components/switch/TEMPLATE.md
  packages/web-vue/components/switch/__demo__/color.md
  packages/web-vue/components/switch/__demo__/value.md
  packages/web-vue/components/switch/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/switch/__test__/index.test.ts
  packages/web-vue/components/switch/switch.vue
Labels: ✨ feature

#445 fix(badge): do not render badge when count is 0
  packages/web-vue/components/badge/__demo__/max.md
  packages/web-vue/components/badge/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/badge/badge.tsx
Labels: 🐞 bug

#449 feat(drawer): add unmount-on-close prop
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/drawer/drawer.vue
Labels: ✨ feature

#453 fix(modal): fix button text problem
  packages/web-vue/components/modal/modal.vue
Labels: 🐞 bug

#452 chore(input-number): modify change event
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/TEMPLATE.md
  packages/web-vue/components/input-number/__demo__/basic.md
  packages/web-vue/components/input-number/__demo__/prefix.md
  packages/web-vue/components/input-number/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-number/input-number.tsx
Labels: ✨ feature

#455 feat(icon): add size prop
  packages/arco-vue-docs/pages/icon/icon-demo.vue
  packages/arco-vue-scripts/package.json
  packages/arco-vue-scripts/src/scripts/build-style/index.ts
  packages/arco-vue-scripts/src/scripts/icongen/svgo.config.ts
  packages/arco-vue-scripts/src/scripts/icongen/vue-template.ts
  packages/web-vue/components/_utils/vue-utils.ts
Labels: ✨ feature

#456 fix(table): fix scroll style problem
  packages/web-vue/components/table/style/index.less
Labels: 🔮 style

#457 fix(upload): fix error
  packages/web-vue/components/upload/upload-button.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: 🐞 bug

#459 fix(modal): fix style problem
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/modal/style/index.less
Labels: 🐞 bug

#472 fix(date-picker): readonly is invalid
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: 🐞 bug

#471 feat(row): add property `wrap`
  packages/web-vue/components/grid/README.en-US.md
  packages/web-vue/components/grid/README.zh-CN.md
  packages/web-vue/components/grid/grid-row.vue
  packages/web-vue/components/grid/style/row.less
Labels: ✨ feature

#470 feat(descriptions): supplement slot params
  packages/web-vue/components/descriptions/README.en-US.md
  packages/web-vue/components/descriptions/README.zh-CN.md
  packages/web-vue/components/descriptions/descriptions.tsx
Labels: ✨ feature

#460 style: opt table style
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/style/token.less
  packages/web-vue/components/table/table-col-group.vue
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-operation-th.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: 🔮 style

#484 docs: add on-demand import
  packages/arco-vue-docs/docs/dark.en-US.md
  packages/arco-vue-docs/docs/dark.zh-CN.md
  packages/arco-vue-docs/docs/i18n.en-US.md
  packages/arco-vue-docs/docs/i18n.zh-CN.md
  packages/arco-vue-docs/docs/start.en-US.md
  packages/arco-vue-docs/docs/start.zh-CN.md
  packages/arco-vue-docs/docs/theme.en-US.md
  packages/arco-vue-docs/docs/theme.zh-CN.md
Labels: 📖 documentation

#476 feat(cascader): add loadMore prop
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/TEMPLATE.md
  packages/web-vue/components/cascader/__demo__/basic.md
  packages/web-vue/components/cascader/__demo__/check-strictly.md
  packages/web-vue/components/cascader/__demo__/clear.md
  packages/web-vue/components/cascader/__demo__/format.md
  packages/web-vue/components/cascader/__demo__/lazy-load.md
  packages/web-vue/components/cascader/__demo__/multiple.md
  packages/web-vue/components/cascader/__demo__/path.md
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/context.ts
  packages/web-vue/components/cascader/hooks/use-selected-path.ts
  packages/web-vue/components/cascader/utils.ts
Labels: ✨ feature

#477 fix(steps): fix nextError style problem
  packages/web-vue/components/steps/step.vue
  packages/web-vue/components/steps/steps.tsx
Labels: 🔮 style

#478 fix(table): fix sorter problem
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#480 fix(form): fix help error
  packages/web-vue/components/form/form-item-message.vue
  packages/web-vue/components/form/utils.ts
Labels: 🐞 bug

#481 fix(input-tag): fix composition problem
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/select/__demo__/group.md
  packages/web-vue/components/select/__demo__/search.md
Labels: 🐞 bug

#483 feat(upload): add showLink prop
  packages/web-vue/components/upload/context.ts
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: ✨ feature

#482 feat(auto-complete): add input slots & option slot
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/mention/style/index.less
  packages/web-vue/components/mention/style/index.ts
  packages/web-vue/components/mention/style/token.less
  packages/web-vue/components/textarea/textarea.vue
Labels: ✨ feature

#485 feat(table): add loadMore & alignLeft
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/__demo__/expand.md
  packages/web-vue/components/table/__demo__/fixed.md
  packages/web-vue/components/table/__demo__/lazy-load.md
  packages/web-vue/components/table/__demo__/sort.md
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/style/token.less
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#487 fix(pagination): fix jumper problem
  packages/web-vue/components/pagination/__demo__/custom.md
  packages/web-vue/components/pagination/page-jumper.vue
Labels: 🐞 bug

#488 chore(form): chore form
  packages/web-vue/components/auto-complete/README.en-US.md
  packages/web-vue/components/auto-complete/README.zh-CN.md
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/__demo__/extra.md
  packages/web-vue/components/form/__demo__/layout.md
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/index.less
  packages/web-vue/components/input/README.en-US.md
  packages/web-vue/components/input/README.zh-CN.md
  packages/web-vue/components/mention/README.en-US.md
  packages/web-vue/components/mention/README.zh-CN.md
  packages/web-vue/components/mention/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/__demo__/notice.md
  packages/web-vue/components/pagination/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/slider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/steps/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/textarea/README.en-US.md
  packages/web-vue/components/textarea/README.zh-CN.md
  packages/web-vue/components/textarea/textarea.vue
  packages/web-vue/components/upload/README.en-US.md
  packages/web-vue/components/upload/README.zh-CN.md
  packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
Labels: ✨ feature
