Repository arco-design/arco-design-vue, pull requests merged in 2021-11, with the labels that each got.

#49 refactor(collapse): refactor repeat code
  packages/web-vue/components/collapse/collapse.vue
Labels: good first issue

#63 fix(input): fix input-search & input-password loss slot
  packages/web-vue/components/input/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input/index.ts
  packages/web-vue/components/input/input-password.vue
  packages/web-vue/components/input/input-search.tsx
  packages/web-vue/components/input/input-search.vue
Labels: bug

#70 style(input): add margin left to clear icon
  packages/web-vue/components/input/style/input.less
  packages/web-vue/components/input/style/token.less
Labels: bug

#75 fix(input-number): fix render default arrow caused by form-item attrs contain type and not effect when modelValue is 0
  packages/web-vue/components/input-number/input-number.tsx
Labels: bug

#85 Add a slot named error-icon to support custom error status icon
  .vscode/settings.json
  packages/web-vue/components/image/README.en-US.md
  packages/web-vue/components/image/README.zh-CN.md
  packages/web-vue/components/image/image.vue
Labels: feature

#105 fix/feat(popconfirm): fix the problem of invalid button props
  packages/web-vue/components/popconfirm/popconfirm.vue
Labels: bug

#113 fix(textarea): fix maximum call of onUpdate
  packages/web-vue/components/textarea/textarea.vue
Labels: bug

#114 fix(input-number): fix negative wrong
  packages/web-vue/components/input-number/input-number.tsx
Labels: bug

#115 fix(image): height does not take effect
  packages/web-vue/components/image/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/image/image.vue
Labels: bug

#116 fix(modal): fix invalid title props
  packages/web-vue/components/modal/modal.vue
Labels: bug

#121 fix(typography): the problem of unable input
  packages/web-vue/components/typography/edit-content.vue
Labels: bug

#123 fix(upload): fix computed isMax
  packages/web-vue/components/upload/upload.tsx
Labels: bug

#126 fix(trigger): fix disabled error
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: bug

#127 fix(table): fix the group header problem
  packages/web-vue/components/table/__demo__/custom.md
  packages/web-vue/components/table/__demo__/fixed.md
  packages/web-vue/components/table/table.tsx
Labels: bug

#128 feat(table): add rowKey and expand-row slot
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/__demo__/row-selection.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: feature

#129 fix(virtual-list): reset itemRenderCache when internalData changes
  packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
Labels: bug

#131 fix(tree): the prop default-checked-key does not take effect
  packages/web-vue/components/tree/hooks/use-checked-state.ts
Labels: bug

#147 fix: the selected state of parent menu is invalid in custom component
  packages/web-vue-storybook/.eslintignore
  packages/web-vue-storybook/stories/components/custom-menu.vue
  packages/web-vue-storybook/stories/components/menu.vue
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/menu/context.ts
  packages/web-vue/components/menu/hooks/use-menu-data-collector.ts
  packages/web-vue/components/menu/interface.ts
  packages/web-vue/components/menu/item.tsx
  packages/web-vue/components/menu/menu.tsx
  packages/web-vue/components/menu/sub-menu-inline.vue
  packages/web-vue/components/menu/sub-menu-pop.vue
  packages/web-vue/components/menu/sub-menu.tsx
  packages/web-vue/components/modal/modal.vue
Labels: bug

#162 fix(trigger): fix the problem of svg position error
  packages/web-vue/components/trigger/utils.ts
Labels: bug

#161 fix(input-tag): fix tag can be close in the disabled state
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: bug

#165 site: add vue page_view tracker
  packages/arco-vue-docs-navbar/package.json
  packages/arco-vue-docs/app.vue
  packages/arco-vue-docs/package.json
  yarn.lock
Labels: docs

#160 style(image): set the max size of error to fit parent
  packages/web-vue/components/image/__demo__/progressive-loader.md
  packages/web-vue/components/image/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/image/image.vue
  packages/web-vue/components/image/style/image.less
Labels: enhancement

#167 feat(zindex): manage the zindex of modal/drawer/image.preview
  packages/web-vue/components/_hooks/use-popup-manager.ts
  packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/image/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/image/preview.vue
  packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/modal/modal.vue
Labels: enhancement

#174 feat(upload): add events and slots
  packages/web-vue/components/_utils/is.ts
  packages/web-vue/components/upload/README.en-US.md
  packages/web-vue/components/upload/README.zh-CN.md
  packages/web-vue/components/upload/interfaces.ts
  packages/web-vue/components/upload/upload-button.tsx
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload-list.tsx
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload.tsx
  packages/web-vue/components/upload/utils.tsx
Labels: feature

#169 feat(tree): add type number for key
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/hooks/use-filter-tree-node.ts
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree-select/interface.ts
  packages/web-vue/components/tree-select/panel.vue
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/base-node.vue
  packages/web-vue/components/tree/context.ts
  packages/web-vue/components/tree/hooks/use-checked-state.ts
  packages/web-vue/components/tree/hooks/use-draggable.ts
  packages/web-vue/components/tree/hooks/use-node-key.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/transition-node-list.vue
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/index.ts
  packages/web-vue/components/tree/utils/tree-data.ts
Labels: enhancement, feature

#173 fix(form): fix the field is null
  packages/web-vue/components/_utils/get-value-by-path.ts
  packages/web-vue/components/table/utils.ts
Labels: bug

#170 feat(select): add VNode label support and option slot
  packages/web-vue/components/_components/dropdown/interface.ts
  packages/web-vue/components/_components/dropdown/utils.ts
  packages/web-vue/components/_utils/vue-utils.ts
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/TEMPLATE.md
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/select/utils.ts
Labels: feature

#171 fix(input-tag): fix composition & press enter problem
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input-tag/style/input-tag.less
  packages/web-vue/components/input/input.tsx
Labels: bug

#176 feat(cascader): add number value & VNode label support
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/TEMPLATE.md
  packages/web-vue/components/cascader/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/interface.ts
  packages/web-vue/components/cascader/utils.ts
Labels: feature

#175 fix(cascader): fix search panel not scroll
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/style/index.less
Labels: bug

#172 feat(drawer): add width & height string support
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/drawer.vue
Labels: feature

#185 fix(tree-select): cannot select the option with key 0
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree/tree.vue
Labels: bug

#184 fix: fix input component can't focus on popup
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/textarea/textarea.vue
Labels: bug

#183 fix(select): move label render to render prop
  packages/web-vue/components/_components/dropdown/dropdown-option.vue
  packages/web-vue/components/_components/dropdown/interface.ts
  packages/web-vue/components/_components/dropdown/utils.ts
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/interface.ts
  packages/web-vue/components/cascader/utils.ts
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/TEMPLATE.md
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/select/utils.ts
Labels: feature

#182 fix: fix z-index problem
  packages/web-vue/components/_hooks/use-popup-manager.ts
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/image/preview.vue
  packages/web-vue/components/message/index.ts
  packages/web-vue/components/message/message-list.tsx
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/notification/index.ts
  packages/web-vue/components/notification/notification-list.tsx
  packages/web-vue/components/select/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/tooltip/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/trigger/trigger.tsx
Labels: bug

#196 fix: fix input component focus problem
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/textarea/textarea.vue
Labels: bug

#198 fix(upload): fix image name overflow problem
  packages/web-vue/components/upload/style/index.less
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload-list.tsx
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: bug

#199 feat(textarea): add wordLength prop
  packages/web-vue/components/textarea/textarea.vue
Labels: feature

#200 fix(select): fix option slot no data
  packages/web-vue/components/select/select.tsx
Labels: bug

#168 feat(tree-select): support the slots of tree
  packages/web-vue/components/_utils/pick-sub-comp-slots.ts
  packages/web-vue/components/tree-select/panel.tsx
  packages/web-vue/components/tree-select/tree-select.vue
Labels: feature

#193 style(menu): pop menu adapts to dark theme
  packages/web-vue/components/menu/style/index.less
  packages/web-vue/components/menu/style/token.less
  packages/web-vue/components/menu/sub-menu-pop.vue
Labels: enhancement

#195 fix(date-picker): fix the problem of invalid verification
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/time-picker/time-picker.vue
  packages/web-vue/components/tree-select/tree-select.vue
Labels: bug

#201 feat(select): add footer slot
  packages/web-vue/components/_components/dropdown/dropdown.vue
  packages/web-vue/components/dropdown/style/index.less
  packages/web-vue/components/select/select.tsx
Labels: feature

#202 feat(input-tag): add backspace support
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: feature

#244 fix(trigger): fix nest problem
  packages/web-vue/components/trigger/__demo__/nest.md
  packages/web-vue/components/trigger/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/trigger/context.ts
  packages/web-vue/components/trigger/trigger.tsx
Labels: bug

#224 fix(page-header): fix dividing will also be displayed when there is no subtitle
  packages/web-vue/components/page-header/page-header.vue
Labels: bug

#210 fix(table): fix expand button trigger form submit
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/table-operation-td.tsx
Labels: bug

#209 fix(steps): fix the problem of unavailable step status
  packages/web-vue/components/_utils/vue-utils.ts
  packages/web-vue/components/breadcrumb/breadcrumb.tsx
  packages/web-vue/components/steps/steps.tsx
Labels: bug

#208 fix: style of form item extra
  packages/web-vue/components/form/style/index.less
Labels: bug

#247 fix: jsx prop support array
  packages/web-vue/components/_utils/types.ts
  packages/web-vue/components/affix/affix.vue
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/checkbox/checkbox-group.vue
  packages/web-vue/components/checkbox/checkbox.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input-search.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/popover/popover.vue
  packages/web-vue/components/radio/radio-group.vue
  packages/web-vue/components/radio/radio.vue
  packages/web-vue/components/rate/rate.tsx
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/slider/slider.vue
  packages/web-vue/components/switch/switch.vue
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/tag/tag.vue
  packages/web-vue/components/textarea/textarea.vue
  packages/web-vue/components/time-picker/time-picker.vue
  packages/web-vue/components/transfer/transfer.vue
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: bug

#246 feat: add collapse token
  packages/web-vue/components/collapse/style/index.less
  packages/web-vue/components/collapse/style/token.less
Labels: style

#249 feat: add comment token
  packages/web-vue/components/comment/style/token.less
Labels: style

#27 textarea add slot
  packages/web-vue/components/textarea/textarea.vue
Labels: feature

#205 Feat mention feat mention support ArcoTextarea(rows), onSearch
  packages/web-vue/components/mention/README.en-US.md
  packages/web-vue/components/mention/README.zh-CN.md
  packages/web-vue/components/mention/__demo__/basic.md
  packages/web-vue/components/mention/__demo__/prefix.md
  packages/web-vue/components/mention/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/mention/mention.tsx
Labels: ✨ enhancement

#226 feat: Link supports icon property & hoverable property
  packages/web-vue/components/card/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/link/README.en-US.md
  packages/web-vue/components/link/README.zh-CN.md
  packages/web-vue/components/link/TEMPLATE.md
  packages/web-vue/components/link/__demo__/hoverable.md
  packages/web-vue/components/link/__demo__/icon.md
  packages/web-vue/components/link/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/link/link.vue
  packages/web-vue/components/link/style/index.less
  packages/web-vue/components/link/style/token.less
  packages/web-vue/components/style/theme/css-variables.less
Labels: ✨ enhancement

#276 fix(steps): style problem
  packages/web-vue/components/steps/style/circle.less
Labels: 🔮 style

#275 feat(pagination): add base-size & buffer-size
  packages/web-vue/components/pagination/README.en-US.md
  packages/web-vue/components/pagination/README.zh-CN.md
  packages/web-vue/components/pagination/pagination.tsx
Labels: ✨ enhancement

#264 fix(menu):Horizontal menu items are not displayed normally when they are collapsed and then expanded
  packages/web-vue-storybook/stories/components/menu.vue
  packages/web-vue/components/layout/__demo__/custom-icon.md
  packages/web-vue/components/layout/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/__demo__/sub-menu.md
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/menu/overflow-wrap.tsx
Labels: 🐞 bug

#274 fix(icon): style problem
  packages/web-vue/components/style/icon.less
Labels: 🔮 style

#273 fix(input): fix pressEnter problem
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
Labels: 🐞 bug

#272 feat(scripts): add jsongen command
  packages/arco-vue-scripts/package.json
  packages/arco-vue-scripts/src/index.ts
  packages/arco-vue-scripts/src/scripts/docgen/index.ts
  packages/arco-vue-scripts/src/scripts/jsongen/index.ts
  packages/arco-vue-scripts/src/utils/get-package.ts
  packages/web-vue/.gitignore
  packages/web-vue/package.json
Labels: ✨ enhancement

#271 feat(form): add form rules prop
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/context.ts
  packages/web-vue/components/form/form-item.tsx
  packages/web-vue/components/form/form.vue
Labels: ✨ enhancement

#270 feat(dropdown): add disabled prop
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/__demo__/basic.md
  packages/web-vue/components/dropdown/dropdown-option.vue
  packages/web-vue/components/dropdown/dropdown-submenu.vue
Labels: ✨ enhancement

#269 feat(desc): modify desc value style
  packages/web-vue/components/descriptions/style/index.less
Labels: 🔮 style

#242 feat: Avatar supports maxStyle & maxPopoverTriggerProps property
  packages/web-vue/components/avatar/README.en-US.md
  packages/web-vue/components/avatar/README.zh-CN.md
  packages/web-vue/components/avatar/avatar-group.tsx
  packages/web-vue/components/avatar/avatar.vue
  packages/web-vue/components/avatar/style/index.less
  packages/web-vue/components/avatar/style/token.less
Labels: feature

#268 feat(desc): add align prop
  packages/web-vue/components/_utils/constant.ts
  packages/web-vue/components/descriptions/README.en-US.md
  packages/web-vue/components/descriptions/README.zh-CN.md
  packages/web-vue/components/descriptions/__demo__/align.md
  packages/web-vue/components/descriptions/__demo__/layout.md
  packages/web-vue/components/descriptions/descriptions.tsx
Labels: ✨ enhancement

#260 fix(tree): let the content of tree node centerd in vertical
  packages/web-vue/components/tree/style/index.less
Labels: 🔮 style

#266 feat(table): add footer slot
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table.tsx
Labels: ✨ enhancement

#229 feat: add on-before-ok to async close
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/__demo__/async.md
  packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/__demo__/async.md
  packages/web-vue/components/modal/__demo__/basic.md
  packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/popconfirm/README.en-US.md
  packages/web-vue/components/popconfirm/README.zh-CN.md
  packages/web-vue/components/popconfirm/__demo__/async.md
  packages/web-vue/components/popconfirm/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/popconfirm/popconfirm.vue
Labels: feature

#277 feat(progress): add trackColor prop
  packages/web-vue/components/progress/README.en-US.md
  packages/web-vue/components/progress/README.zh-CN.md
  packages/web-vue/components/progress/circle.vue
  packages/web-vue/components/progress/line.vue
  packages/web-vue/components/progress/progress.vue
  packages/web-vue/components/progress/steps.vue
Labels: ✨ enhancement
