Repository arco-design/arco-design-vue, pull requests merged in 2022-09, with the labels that each got.

#1589 docs: vue documentation link migration
  packages/arco-vue-docs/docs/pro/directory.en-US.md
  packages/arco-vue-docs/docs/pro/directory.zh-CN.md
Labels: type: docs

#1436 fix(input-password): fix icon error for issues #1434
  packages/web-vue/components/input/input-password.vue
Labels: type: enhancement

#1500 feat(breadcrumb): support routes and more props config
  packages/web-vue/components/breadcrumb/README.en-US.md
  packages/web-vue/components/breadcrumb/README.zh-CN.md
  packages/web-vue/components/breadcrumb/TEMPLATE.md
  packages/web-vue/components/breadcrumb/__demo__/dropdown.md
  packages/web-vue/components/breadcrumb/__demo__/ellipsis.md
  packages/web-vue/components/breadcrumb/__demo__/icon.md
  packages/web-vue/components/breadcrumb/__demo__/routes.md
  packages/web-vue/components/breadcrumb/__demo__/separator.md
  packages/web-vue/components/breadcrumb/__demo__/size.md
  packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
  packages/web-vue/components/breadcrumb/breadcrumb.tsx
  packages/web-vue/components/breadcrumb/context.ts
  packages/web-vue/components/breadcrumb/interface.ts
Labels: type: enhancement, type: feature request

#1551 feat: add locale zhTW and ptPT
  packages/web-vue/components/locale/lang/pt-pt.ts
  packages/web-vue/components/locale/lang/zh-tw.ts
Labels: type: feature request

#1544 feat(alert): support custom close element
  packages/web-vue/components/alert/README.en-US.md
  packages/web-vue/components/alert/README.zh-CN.md
  packages/web-vue/components/alert/TEMPLATE.md
  packages/web-vue/components/alert/__demo__/action.md
  packages/web-vue/components/alert/__demo__/close-element.md
  packages/web-vue/components/alert/alert.vue
Labels: type: feature request

#1534 feat(image): add fit props
  packages/web-vue/components/image/image.vue
  packages/web-vue/components/image/interface.ts
Labels: type: feature request

#1595 Flsion/feat image
  packages/web-vue/components/image/image.vue
Labels: type: feature request

#1594 feat(breadcrumb): add ts export & breadcrumb customUrl
  packages/web-vue/components/breadcrumb/__demo__/dropdown.md
  packages/web-vue/components/breadcrumb/__demo__/routes.md
  packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
  packages/web-vue/components/breadcrumb/breadcrumb.tsx
  packages/web-vue/components/breadcrumb/index.ts
  packages/web-vue/components/breadcrumb/interface.ts
  packages/web-vue/components/dropdown/dropdown.vue
  packages/web-vue/components/dropdown/index.ts
  packages/web-vue/components/dropdown/interface.ts
  packages/web-vue/components/index.ts
Labels: type: feature request

#1580 enhance(table): support custom cell class
  packages/web-vue/components/_utils/types.ts
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/hooks/use-expand.ts
  packages/web-vue/components/table/hooks/use-row-selection.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table-col-group.vue
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: type: feature request

#1540 feat(checkbox-group): support limit the maximum number of options
  packages/web-vue/components/checkbox/README.en-US.md
  packages/web-vue/components/checkbox/README.zh-CN.md
  packages/web-vue/components/checkbox/TEMPLATE.md
  packages/web-vue/components/checkbox/__demo__/custom.md
  packages/web-vue/components/checkbox/__demo__/group.md
  packages/web-vue/components/checkbox/__demo__/limit.md
  packages/web-vue/components/checkbox/__demo__/options.md
  packages/web-vue/components/checkbox/checkbox-group.tsx
  packages/web-vue/components/checkbox/checkbox.tsx
  packages/web-vue/components/checkbox/context.ts
Labels: type: feature request

#1571 feat: add layout type definition
  packages/web-vue/components/index.ts
  packages/web-vue/components/layout/index.ts
  packages/web-vue/components/layout/interface.ts
Labels: type: feature request

#1499 feat(page-header): custom back-icon slot
  packages/web-vue/components/page-header/README.en-US.md
  packages/web-vue/components/page-header/README.zh-CN.md
  packages/web-vue/components/page-header/__demo__/basic.md
  packages/web-vue/components/page-header/__demo__/breadcrumb.md
  packages/web-vue/components/page-header/__demo__/content.md
  packages/web-vue/components/page-header/__demo__/transparent.md
  packages/web-vue/components/page-header/page-header.vue
Labels: type: feature request

#1620 docs(table): fix row-calss function support version #1553
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/table.tsx
Labels: type: docs

#1623 enhance(modal): support on-before-ok prop receive async function
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/drawer/interface.ts
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/__demo__/async.md
  packages/web-vue/components/modal/interface.ts
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/popconfirm/README.en-US.md
  packages/web-vue/components/popconfirm/README.zh-CN.md
  packages/web-vue/components/popconfirm/popconfirm.vue
Labels: type: enhancement

#1622 docs(input-tag): update doc
  packages/web-vue/components/input-tag/README.en-US.md
  packages/web-vue/components/input-tag/README.zh-CN.md
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: type: docs

#1607 fix(select): fix option slot parameters
  packages/web-vue/components/select/select.tsx
Labels: type: 🐞 bug

#1597 docs(split): fix text error
  packages/web-vue/components/split/README.zh-CN.md
  packages/web-vue/components/split/TEMPLATE.md
  packages/web-vue/components/split/__demo__/basic.md
  packages/web-vue/components/split/__demo__/nested.md
Labels: type: docs

#1614 docs: virtual v2 doc & usage
  packages/arco-vue-docs/docs/faq.en-US.md
  packages/arco-vue-docs/docs/faq.zh-CN.md
  packages/web-vue/components/_components/virtual-list-v2/interface.ts
  packages/web-vue/components/list/README.en-US.md
  packages/web-vue/components/list/README.zh-CN.md
  packages/web-vue/components/list/TEMPLATE.md
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/TEMPLATE.md
  packages/web-vue/components/select/hooks/use-select.ts
  packages/web-vue/components/select/interface.ts
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/TEMPLATE.md
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
Labels: type: docs, type: typescript

#1626 feat(switch): add beforeChange intercept change event
  packages/web-vue/components/switch/README.en-US.md
  packages/web-vue/components/switch/README.zh-CN.md
  packages/web-vue/components/switch/TEMPLATE.md
  packages/web-vue/components/switch/__demo__/change-intercept.md
  packages/web-vue/components/switch/switch.vue
Labels: type: docs, type: feature request

#1616 feat(link): add loading prop
  packages/web-vue/components/link/README.en-US.md
  packages/web-vue/components/link/README.zh-CN.md
  packages/web-vue/components/link/TEMPLATE.md
  packages/web-vue/components/link/__demo__/loading.md
  packages/web-vue/components/link/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/link/link.vue
  packages/web-vue/components/link/style/index.less
  packages/web-vue/components/link/style/token.less
Labels: type: feature request

#1635 feat: add css ellipsis
  packages/web-vue/components/typography/__demo__/ellipsis.md
  packages/web-vue/components/typography/base.tsx
  packages/web-vue/components/typography/interface.ts
  packages/web-vue/components/typography/style/index.less
Labels: type: feature request

#1634 Flsion/feat scrollbar
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/arco-vue-scripts/src/scripts/changelog/utils.ts
  packages/web-vue/components/_hooks/use-component-ref.ts
  packages/web-vue/components/_utils/array.ts
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/cascader/base-cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/style/index.less
  packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/dropdown/dropdown-panel.vue
  packages/web-vue/components/index.less
  packages/web-vue/components/index.ts
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/mention/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/overflow-list/CHANGELOG.md
  packages/web-vue/components/overflow-list/CHANGELOG.zh-CN.md
  packages/web-vue/components/overflow-list/README.en-US.md
  packages/web-vue/components/overflow-list/README.zh-CN.md
  packages/web-vue/components/overflow-list/TEMPLATE.md
  packages/web-vue/components/overflow-list/__demo__/basic.md
  packages/web-vue/components/overflow-list/__demo__/from.md
  packages/web-vue/components/overflow-list/index.ts
  packages/web-vue/components/overflow-list/overflow-list.tsx
  packages/web-vue/components/overflow-list/style/index.less
  packages/web-vue/components/overflow-list/style/index.ts
  packages/web-vue/components/scrollbar/CHANGELOG.md
  packages/web-vue/components/scrollbar/CHANGELOG.zh-CN.md
  packages/web-vue/components/scrollbar/README.en-US.md
  packages/web-vue/components/scrollbar/README.zh-CN.md
  packages/web-vue/components/scrollbar/TEMPLATE.md
  packages/web-vue/components/scrollbar/__demo__/basic.md
  packages/web-vue/components/scrollbar/__demo__/type.md
  packages/web-vue/components/scrollbar/index.ts
  packages/web-vue/components/scrollbar/interface.ts
  packages/web-vue/components/scrollbar/scrollbar.vue
  packages/web-vue/components/scrollbar/style/index.less
  packages/web-vue/components/scrollbar/style/index.ts
  packages/web-vue/components/scrollbar/style/token.less
  packages/web-vue/components/scrollbar/thumb.vue
  packages/web-vue/components/select/select-dropdown.vue
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/transfer/__test__/__snapshots__/demo.test.ts.snap
Labels: type: feature request

#1655 fix(scrollbar): fix some problem
  packages/web-vue/components/_hooks/use-component-ref.ts
  packages/web-vue/components/cascader/style/index.ts
  packages/web-vue/components/dropdown/style/index.ts
  packages/web-vue/components/list/style/index.ts
  packages/web-vue/components/scrollbar/scrollbar.vue
  packages/web-vue/components/scrollbar/style/index.less
  packages/web-vue/components/select/hooks/use-select.ts
  packages/web-vue/components/select/select-dropdown.vue
  packages/web-vue/components/select/style/index.ts
  packages/web-vue/components/table/style/index.ts
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#1650 fix: on-before-ok bugs
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/popconfirm/popconfirm.vue
Labels: type: enhancement

#1619 feat(icon): suport generate types
  packages/arco-vue-scripts/src/scripts/icongen/index.ts
  packages/arco-vue-scripts/src/scripts/icongen/vue-template.ts
  packages/web-vue/components/icon-components.ts
Labels: type: typescript

#1658 fix(scrollbar): fix some problem
  packages/web-vue/components/_hooks/use-component-ref.ts
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/list/style/index.less
  packages/web-vue/components/scrollbar/scrollbar.vue
Labels: type: 🐞 bug

#1673 enhance(empty): optimize custom display order
  packages/web-vue/components/empty/empty.tsx
Labels: type: enhancement

#1672 enhance(input): enhance max limit
  packages/web-vue/components/_hooks/use-cursor.ts
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/textarea/textarea.vue
Labels: type: enhancement

#1287 feat(overflow-list): add overflow change event
  packages/web-vue/components/overflow-list/README.en-US.md
  packages/web-vue/components/overflow-list/README.zh-CN.md
  packages/web-vue/components/overflow-list/overflow-list.tsx
Labels: type: enhancement, type: feature request

#1662 fix: fix update tooltip visible after content change
  packages/web-vue/components/_components/auto-tooltip/auto-tooltip.tsx
Labels: type: 🐞 bug

#1668 fix(imagePreview): do not display toolbar when actions layout is empty
  packages/web-vue/components/image/preview.vue
Labels: type: enhancement

#1667 fix(table): fix type definition
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/interface.ts
Labels: type: 🐞 bug, type: typescript

#1704 fix(tabs): fix style problem
  packages/web-vue/components/tabs/tabs-tab.vue
Labels: type: 🔮 style

#1703 fix(select): fix custom tag color problem
  packages/web-vue/components/input-tag/style/input-tag.less
  packages/web-vue/components/tag/style/index.less
Labels: type: 🔮 style

#1702 enhance(button): use flex layout
  packages/web-vue/components/button/style/index.less
  packages/web-vue/components/link/style/index.less
Labels: type: enhancement

#1696 fix(modal): fix modal close problem
  packages/web-vue/components/drawer/index.ts
  packages/web-vue/components/modal/index.tsx
Labels: type: enhancement

#1659 fix: fix popup stack
  packages/web-vue/components/_hooks/use-popup-manager.ts
Labels: type: 🐞 bug

#1680 style(collapse): adjust the padding of collapse-item-content when expand-icon is on the right
  packages/web-vue/components/collapse/style/index.less
Labels: type: 🔮 style

#1707 fix(table): fix default sorter&filters invalid in template
  packages/web-vue/components/table/__demo__/summary.md
  packages/web-vue/components/table/hooks/use-filter.ts
  packages/web-vue/components/table/hooks/use-sorter.ts
Labels: type: 🐞 bug
