Repository arco-design/arco-design-vue, pull requests merged in 2022-05, with the labels that each got.

#1058 feat(checkbox-group): support options prop children
  packages/web-vue/components/checkbox/README.en-US.md
  packages/web-vue/components/checkbox/README.zh-CN.md
  packages/web-vue/components/checkbox/TEMPLATE.md
  packages/web-vue/components/checkbox/__demo__/options.md
  packages/web-vue/components/checkbox/checkbox-group.tsx
  packages/web-vue/components/checkbox/index.ts
  packages/web-vue/components/checkbox/interface.ts
Labels: ✨ feature

#1115 feat(input-number): add modelEvent prop
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/TEMPLATE.md
  packages/web-vue/components/input-number/__demo__/model.md
  packages/web-vue/components/input-number/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-number/input-number.tsx
Labels: ✨ feature

#1090 feat(radio): radio-group support options
  packages/web-vue/components/radio/README.en-US.md
  packages/web-vue/components/radio/README.zh-CN.md
  packages/web-vue/components/radio/TEMPLATE.md
  packages/web-vue/components/radio/__demo__/options.md
  packages/web-vue/components/radio/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/radio/context.ts
  packages/web-vue/components/radio/index.ts
  packages/web-vue/components/radio/interface.ts
  packages/web-vue/components/radio/radio-group.tsx
  packages/web-vue/components/radio/radio.tsx
Labels: ✨ feature

#1070 fix: fix model fullscreen dislocation position
  packages/web-vue/components/modal/modal.vue
Labels: 🐞 bug

#1095 fix(message): fix message clear problem
  packages/web-vue/components/message/index.ts
  packages/web-vue/components/notification/index.ts
Labels: 🐞 bug

#1112 fix(date-picker): week and quarter has a wrong value
  packages/web-vue/components/date-picker/pickers/quarter-picker.tsx
  packages/web-vue/components/date-picker/pickers/week-picker.tsx
Labels: 🐞 bug

#1113 fix(tree): expandAll is invalid when the type of key is number
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree/base-node.vue
  packages/web-vue/components/tree/hooks/use-checked-state.ts
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/index.ts
Labels: 🐞 bug

#1102 enhance(carousel): ARIA improvement
  packages/web-vue/components/carousel/README.en-US.md
  packages/web-vue/components/carousel/README.zh-CN.md
  packages/web-vue/components/carousel/TEMPLATE.md
  packages/web-vue/components/carousel/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/carousel/carousel-item.vue
  packages/web-vue/components/carousel/carousel.tsx
  packages/web-vue/components/carousel/context.ts
  packages/web-vue/components/carousel/index.ts
Labels: 💎 enhancement

#1104 enhance(divider): ARIA improvement
  packages/web-vue/components/divider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/divider/divider.tsx
Labels: 💎 enhancement

#1105 enhance(list): ARIA improvement
  packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/list/list-item.tsx
  packages/web-vue/components/list/list.tsx
Labels: 💎 enhancement

#1106 feat(input): add inputAttrs prop
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/input/input-search.tsx
  packages/web-vue/components/input/input.tsx
Labels: ✨ feature

#1107 feat(tabs): add destroyOnHide prop
  packages/web-vue/components/tabs/README.en-US.md
  packages/web-vue/components/tabs/README.zh-CN.md
  packages/web-vue/components/tabs/context.ts
  packages/web-vue/components/tabs/tab-pane.vue
  packages/web-vue/components/tabs/tabs.tsx
Labels: ✨ feature

#1111 enhance(trigger): support trigger nest
  packages/web-vue/components/image/preview-action.tsx
  packages/web-vue/components/trigger/trigger.tsx
Labels: 💎 enhancement

#1114 fix(select): fix options prop render & tagProps invalid problem
  packages/web-vue/components/_components/input-label/style/input-label.less
  packages/web-vue/components/select/utils.ts
Labels: 🐞 bug, 🔮 style

#1118 feat(table): enhance interface
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/interface.ts
Labels: typescript

#1120 fix(modal): fix interface problem
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/interface.ts
  packages/web-vue/components/modal/modal.vue
Labels: typescript

#1123 fix(pagination): fix size problem on simple
  packages/web-vue/components/pagination/pagination.tsx
Labels: 🐞 bug

#1124 fix(table): fix fixed style problem
  packages/web-vue/components/table/style/index.less
Labels: 🔮 style

#1125 fix(list): fix pagination invalid problem
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/list/use-pagination.ts
Labels: 🐞 bug

#1122 fix(typography): event `edit-end` triggered twice when press enter
  packages/web-vue/components/typography/README.en-US.md
  packages/web-vue/components/typography/README.zh-CN.md
  packages/web-vue/components/typography/base.tsx
Labels: 🐞 bug

#1119 feat(tree): only leaf node can be selected
  packages/web-vue/components/_utils/to-array.ts
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/panel.tsx
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/base-node.vue
  packages/web-vue/components/tree/context.ts
  packages/web-vue/components/tree/hooks/use-tree-data.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/tree-data.ts
Labels: ✨ feature

#1141 fix(select): fix group options problem
  packages/web-vue/components/select/utils.ts
Labels: 🐞 bug

#1161 feat(emits): update components emits
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/split/split.vue
  packages/web-vue/components/time-picker/time-picker.vue
  packages/web-vue/components/tree-select/interface.ts
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/typography/base.tsx
  packages/web-vue/components/typography/operations.vue
Labels: typescript

#1159 feat(scripts): update vite plugin
  packages/arco-vue-scripts/src/configs/vite.material.library.ts
  packages/arco-vue-scripts/src/configs/vite.prod.ts
  packages/arco-vue-scripts/src/plugins/vite-plugin-build-virtual/index.ts
  packages/arco-vue-scripts/src/plugins/vite-plugin-vue-export-helper/index.ts
Labels: ✨ feature

#1133 fix: 文档更新，style样式引入需要打开sideEffect
  packages/arco-vue-docs/docs/start.en-US.md
  packages/arco-vue-docs/docs/start.zh-CN.md
Labels: 📖 documentation

#1147 docs: update vue pro docs
  packages/arco-vue-docs/docs/pro/npm-scripts.en-US.md
  packages/arco-vue-docs/docs/pro/npm-scripts.zh-CN.md
  packages/arco-vue-docs/docs/pro/permission.en-US.md
  packages/arco-vue-docs/docs/pro/permission.zh-CN.md
  packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
  packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
Labels: 📖 documentation

#1173 fix(date-picker): `select time` is not internationalized
  packages/web-vue/components/date-picker/panels/date/index.vue
Labels: 🐞 bug

#1160 feat(emits): update components emits
  packages/web-vue/components/_hooks/use-trigger.ts
  packages/web-vue/components/_utils/types.ts
  packages/web-vue/components/affix/affix.vue
  packages/web-vue/components/alert/alert.vue
  packages/web-vue/components/anchor/anchor.vue
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/back-top/back-top.vue
  packages/web-vue/components/cascader/cascader-panel.vue
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/dropdown/dropdown-button.vue
  packages/web-vue/components/dropdown/dropdown-submenu.vue
  packages/web-vue/components/dropdown/dropdown.vue
  packages/web-vue/components/form/form.vue
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/pagination/pagination.tsx
  packages/web-vue/components/popconfirm/popconfirm.vue
  packages/web-vue/components/popover/popover.vue
  packages/web-vue/components/rate/rate.tsx
  packages/web-vue/components/resize-box/resize-box.vue
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/slider/slider.vue
  packages/web-vue/components/steps/steps.vue
  packages/web-vue/components/switch/switch.vue
  packages/web-vue/components/tabs/tabs.tsx
  packages/web-vue/components/tag/tag.vue
  packages/web-vue/components/textarea/textarea.vue
  packages/web-vue/components/tooltip/tooltip.vue
  packages/web-vue/components/transfer/transfer.vue
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: typescript

#1176 fix(textarea): fix style problem
  packages/web-vue/components/textarea/style/index.less
Labels: 🔮 style

#1177 fix(cascader): fix lazy load problem
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader-panel.vue
  packages/web-vue/components/cascader/utils.ts
Labels: 🐞 bug

#1179 feat(statistic): add placeholder prop
  packages/web-vue/components/statistic/statistic.vue
Labels: ✨ feature

#1180 feat(config): add empty & loading slots
  packages/web-vue/components/config-provider/README.en-US.md
  packages/web-vue/components/config-provider/README.zh-CN.md
  packages/web-vue/components/config-provider/TEMPLATE.md
  packages/web-vue/components/config-provider/__demo__/empty.md
  packages/web-vue/components/config-provider/config-provider.vue
  packages/web-vue/components/empty/TEMPLATE.md
  packages/web-vue/components/empty/empty.tsx
  packages/web-vue/components/empty/empty.vue
  packages/web-vue/components/empty/index.ts
  packages/web-vue/components/spin/spin.tsx
Labels: ✨ feature

#1175 feat(date-picker): Improve the behavior of `shortcut`
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: 💎 enhancement, ✨ feature

#1101 docs: demo code open in stackblitz
  packages/arco-vue-docs/components/cell-code/index.vue
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/package.json
  packages/arco-vue-docs/utils/code-sandbox.ts
  packages/arco-vue-docs/utils/code-stackblitz.ts
  packages/arco-vue-docs/utils/code-template.ts
  yarn.lock
Labels: ✨ feature

#1198 feat(date-picker): add property `show-confirm-btn`
  packages/web-vue-storybook/stories/components/date-picker.vue
  packages/web-vue-storybook/stories/index.stories.ts
  packages/web-vue/components/checkbox/checkbox-group.tsx
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/pickers/date-picker.tsx
  packages/web-vue/components/date-picker/pickers/month-picker.tsx
  packages/web-vue/components/date-picker/pickers/quarter-picker.tsx
  packages/web-vue/components/date-picker/pickers/week-picker.tsx
  packages/web-vue/components/date-picker/pickers/year-picker.tsx
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/link/link.vue
Labels: ✨ feature

#1199 fix(date-picker): only update the date when splicing the time
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/utils/index.ts
Labels: 💎 enhancement

#1202 feat(table): add checkStrictly support
  packages/web-vue/components/_hooks/use-pure-prop.ts
  packages/web-vue/components/_utils/array.ts
  packages/web-vue/components/_utils/is-equal.ts
  packages/web-vue/components/_utils/is.ts
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/__demo__/subtree.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/hooks/use-row-selection.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-operation-th.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: ✨ feature

#1207 fix(tree-select): drag and drop fails when setting fieldNames
  packages/web-vue/components/tree/tree.vue
Labels: 🐞 bug

#1197 docs: add pro faq page
  packages/arco-vue-docs/docs/pro/faq.en-US.md
  packages/arco-vue-docs/docs/pro/faq.zh-CN.md
  packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
  packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
Labels: 📖 documentation

#1196 enhance: ARIA improvement
  packages/web-vue/components/alert/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/alert/alert.vue
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/cascader/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/cascader/base-cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/form-item-message.vue
  packages/web-vue/components/image/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/image/image.vue
  packages/web-vue/components/input-tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/progress/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/slider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/slider/slider-button.vue
  packages/web-vue/components/slider/slider-marks.vue
  packages/web-vue/components/slider/slider.vue
  packages/web-vue/components/tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tag/tag.vue
  packages/web-vue/components/transfer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/transfer/transfer.vue
Labels: 💎 enhancement

#1203 feat(dropdown): add max height support
  packages/web-vue/components/dropdown/__demo__/basic.md
  packages/web-vue/components/dropdown/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/dropdown/context.ts
  packages/web-vue/components/dropdown/dropdown-button.vue
  packages/web-vue/components/dropdown/dropdown-panel.vue
  packages/web-vue/components/dropdown/dropdown-submenu.vue
  packages/web-vue/components/dropdown/dropdown.vue
Labels: ✨ feature

#1206 feat(tree-select): default support to delete selected options by tag
  packages/web-vue-storybook/stories/components/tree-select.vue
  packages/web-vue-storybook/stories/index.stories.ts
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree-select/panel.tsx
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/check-utils.ts
  packages/web-vue/components/tree/utils/index.ts
Labels: ✨ feature

#1204 fix: input problem
  packages/web-vue/components/_hooks/use-input.ts
  packages/web-vue/components/back-top/back-top.vue
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/textarea/textarea.vue
Labels: 🐞 bug
