Repository arco-design/arco-design-vue, pull requests merged in 2022-03, with the labels that each got.

#767 fix(menu): the icon of sub-menu are not centered in vertically
  packages/web-vue/components/menu/style/index.less
Labels: 🐞 bug

#754 feat(date-picker): support quick switching of year and month in the head
  packages/web-vue/components/date-picker/hooks/use-format.ts
  packages/web-vue/components/date-picker/hooks/use-header-value.ts
  packages/web-vue/components/date-picker/panels/date/index.vue
  packages/web-vue/components/date-picker/panels/header.vue
  packages/web-vue/components/date-picker/panels/month/index.vue
  packages/web-vue/components/date-picker/panels/quarter/index.vue
  packages/web-vue/components/date-picker/picker-panel.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/style/index.less
  packages/web-vue/components/date-picker/style/token.less
Labels: ✨ feature

#740 docs(directory): fix the description of the directory for arco-design-pro-vue
  packages/arco-vue-docs/docs/pro/directory.en-US.md
  packages/arco-vue-docs/docs/pro/directory.zh-CN.md
Labels: 📖 documentation

#765 docs: pro document update
  packages/arco-vue-docs/docs/pro/directory.en-US.md
  packages/arco-vue-docs/docs/pro/directory.zh-CN.md
  packages/arco-vue-docs/docs/pro/start.en-US.md
  packages/arco-vue-docs/docs/pro/start.zh-CN.md
Labels: 📖 documentation

#768 fix(form): fix path field error
  packages/web-vue/components/_utils/get-value-by-path.ts
  packages/web-vue/components/form/form-item.vue
Labels: 🐞 bug

#769 feat(checkbox): add slot
  packages/web-vue/components/_components/icon-hover.vue
  packages/web-vue/components/checkbox/README.en-US.md
  packages/web-vue/components/checkbox/README.zh-CN.md
  packages/web-vue/components/checkbox/TEMPLATE.md
  packages/web-vue/components/checkbox/__demo__/custom.md
  packages/web-vue/components/checkbox/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/checkbox/checkbox.vue
  packages/web-vue/components/radio/README.en-US.md
  packages/web-vue/components/radio/README.zh-CN.md
  packages/web-vue/components/radio/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/radio/radio.vue
Labels: ✨ feature

#770 feat(rate): add color prop
  packages/web-vue/components/rate/README.en-US.md
  packages/web-vue/components/rate/README.zh-CN.md
  packages/web-vue/components/rate/TEMPLATE.md
  packages/web-vue/components/rate/__demo__/color.md
  packages/web-vue/components/rate/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/rate/rate.tsx
Labels: ✨ feature

#771 perf(tabs): use context refactor, add autoSwitch prop
  packages/web-vue/components/tabs/README.en-US.md
  packages/web-vue/components/tabs/README.zh-CN.md
  packages/web-vue/components/tabs/TEMPLATE.md
  packages/web-vue/components/tabs/__demo__/editable.md
  packages/web-vue/components/tabs/__demo__/lazy.md
  packages/web-vue/components/tabs/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tabs/__test__/index.test.ts
  packages/web-vue/components/tabs/context.ts
  packages/web-vue/components/tabs/interface.ts
  packages/web-vue/components/tabs/tab-pane.vue
  packages/web-vue/components/tabs/tabs-button.tsx
  packages/web-vue/components/tabs/tabs-nav-ink.vue
  packages/web-vue/components/tabs/tabs-nav.tsx
  packages/web-vue/components/tabs/tabs-tab.vue
  packages/web-vue/components/tabs/tabs.tsx
  packages/web-vue/components/tabs/utils.ts
Labels: ✨ feature

#772 perf(steps): use context refactor
  packages/web-vue/components/steps/TEMPLATE.md
  packages/web-vue/components/steps/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/steps/context.ts
  packages/web-vue/components/steps/index.ts
  packages/web-vue/components/steps/interface.ts
  packages/web-vue/components/steps/step.vue
  packages/web-vue/components/steps/steps.vue
Labels: 💎 enhancement

#773 perf(avatar): use context refactor
  packages/web-vue/components/avatar/README.en-US.md
  packages/web-vue/components/avatar/README.zh-CN.md
  packages/web-vue/components/avatar/avatar-group.tsx
  packages/web-vue/components/avatar/avatar.vue
  packages/web-vue/components/avatar/constants.ts
  packages/web-vue/components/avatar/context.ts
  packages/web-vue/components/avatar/interface.ts
Labels: 💎 enhancement

#774 perf(bread): use context refactor
  packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
  packages/web-vue/components/breadcrumb/breadcrumb.tsx
  packages/web-vue/components/breadcrumb/context.ts
Labels: 💎 enhancement

#775 fix(slider): fix input not trigger change
  packages/web-vue/components/slider/slider.vue
Labels: 🐞 bug

#776 fix(list): use div item
  packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/list/list-item.tsx
Labels: 🐞 bug

#777 fix(select): fix option update error
  packages/web-vue/components/_components/input-label/style/input-label.less
  packages/web-vue/components/_hooks/use-index.ts
  packages/web-vue/components/_utils/is-equal.ts
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/__demo__/basic.md
  packages/web-vue/components/select/__demo__/linkage.md
  packages/web-vue/components/select/__demo__/multiple.md
  packages/web-vue/components/select/__demo__/remote.md
  packages/web-vue/components/select/context.ts
  packages/web-vue/components/select/hooks/use-options.ts
  packages/web-vue/components/select/option.vue
  packages/web-vue/components/select/select.tsx
Labels: 🐞 bug

#778 perf(input): support undefined/null change
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/input-tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/textarea/textarea.vue
Labels: 💎 enhancement

#779 perf(transfer): fix some ts problem
  packages/web-vue/components/transfer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/transfer/context.ts
  packages/web-vue/components/transfer/transfer-list-item.tsx
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/transfer/transfer.vue
Labels: 💎 enhancement

#780 feat(table): support 100% height, add column slotName prop
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/__demo__/custom.md
  packages/web-vue/components/table/__demo__/scroll.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#781 feat(cascader): add option/label slot
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/cascader/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/context.ts
Labels: ✨ feature

#782 feat(volar): add volar support
  packages/web-vue/components/global.d.ts
  packages/web-vue/components/modal/__demo__/async.md
  packages/web-vue/components/trigger/interface.ts
Labels: ✨ feature

#787 fix(tabs): fix init change error
  packages/web-vue/components/tabs/tabs.tsx
Labels: 🐞 bug

#786 fix(upload): fix percent problem
  packages/web-vue/components/upload/upload-progress.tsx
  packages/web-vue/components/upload/utils.tsx
Labels: 🐞 bug

#808 docs: update pro & tabs doc
  packages/arco-vue-docs/docs/pro/directory.zh-CN.md
  packages/web-vue/components/tabs/README.en-US.md
  packages/web-vue/components/tabs/README.zh-CN.md
  packages/web-vue/components/tabs/tabs.tsx
Labels: 📖 documentation

#796 fix(date-picker): the offset of popup is wrong
  packages/web-vue/components/date-picker/range-picker.vue
Labels: 🐞 bug

#800 fix(tree): the rendering process should not be blocked when the node …
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/index.ts
Labels: 🐞 bug

#804 feat(message): add appContext
  packages/web-vue/components/message/README.en-US.md
  packages/web-vue/components/message/README.zh-CN.md
  packages/web-vue/components/message/index.ts
  packages/web-vue/components/message/interface.ts
  packages/web-vue/components/notification/README.en-US.md
  packages/web-vue/components/notification/README.zh-CN.md
  packages/web-vue/components/notification/index.ts
  packages/web-vue/components/notification/interface.ts
Labels: 💎 enhancement

#803 feat(drawer): add hideCancel
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/drawer.vue
Labels: ✨ feature

#802 feat(modal): add draggable, fullscreen and appContext
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/TEMPLATE.md
  packages/web-vue/components/modal/__demo__/draggable.md
  packages/web-vue/components/modal/__demo__/form.md
  packages/web-vue/components/modal/__demo__/fullscreen.md
  packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/hooks/use-draggable.ts
  packages/web-vue/components/modal/index.tsx
  packages/web-vue/components/modal/interface.ts
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/modal/style/index.less
Labels: ✨ feature

#807 fix(form): fix form item array filed & disabled
  packages/web-vue/components/_components/picker/input-range.vue
  packages/web-vue/components/_components/picker/input.vue
  packages/web-vue/components/_utils/get-value-by-path.ts
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/mention/README.en-US.md
  packages/web-vue/components/mention/README.zh-CN.md
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/textarea/textarea.vue
  packages/web-vue/components/time-picker/time-picker.vue
Labels: 🐞 bug

#810 perf(table): modify sorter function params
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#809 feat(tree): support for setting half-checked nodes
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/hooks/use-checked-state.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
Labels: ✨ feature

#812 fix(desc): fix error when data is empty
  packages/web-vue/components/descriptions/descriptions.tsx
Labels: 🐞 bug

#837 feat(tree): add instance method to tree component
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/context.ts
  packages/web-vue/components/tree/hooks/use-checked-state.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/index.ts
Labels: ✨ feature

#833 fix: 🐛 修复slots改变时ellipsisText未变化
  packages/web-vue/components/typography/base.tsx
Labels: 🐞 bug

#839 feat(desc): column prop support ResponsiveValue
  packages/web-vue/components/descriptions/README.en-US.md
  packages/web-vue/components/descriptions/README.zh-CN.md
  packages/web-vue/components/descriptions/__demo__/basic.md
  packages/web-vue/components/descriptions/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/descriptions/descriptions.tsx
Labels: ✨ feature

#838 feat(list): add scroll-loading
  packages/web-vue/components/list/README.en-US.md
  packages/web-vue/components/list/README.zh-CN.md
  packages/web-vue/components/list/__demo__/scroll.md
  packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/transfer/__test__/__snapshots__/demo.test.ts.snap
Labels: ✨ feature

#844 fix(date-picker): the selected event is not triggered when the end time selected
  packages/web-vue/components/date-picker/range-picker.vue
Labels: 🐞 bug

#845 perf(table): use context refactor
  packages/web-vue/components/form/__demo__/status.md
  packages/web-vue/components/select/__demo__/footer.md
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/__demo__/editable.md
  packages/web-vue/components/table/__demo__/scroll.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/hooks/use-column-filter.ts
  packages/web-vue/components/table/hooks/use-column-resize.ts
  packages/web-vue/components/table/hooks/use-column-sorter.ts
  packages/web-vue/components/table/hooks/use-data.ts
  packages/web-vue/components/table/hooks/use-drag.ts
  packages/web-vue/components/table/hooks/use-filter.ts
  packages/web-vue/components/table/hooks/use-row-selection.ts
  packages/web-vue/components/table/hooks/use-sorter.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: ✨ feature

#853 fix(tree): the name of expanded event is wrong
  packages/web-vue/components/tree/tree.vue
Labels: 🐞 bug

#854 fix: fix some style problem
  packages/arco-vue-docs/index.ts
  packages/web-vue/components/form/style/index.less
  packages/web-vue/components/select/option.vue
  packages/web-vue/components/select/style/index.less
  packages/web-vue/components/transfer/style/index.less
  packages/web-vue/components/transfer/transfer-list-item.tsx
Labels: 🔮 style

#856 docs: update state-management-pinia
  packages/arco-vue-docs/docs/pro/state-management-pinia.zh-CN.md
Labels: 📖 documentation

#861 fix(table): fix table-column problem
  packages/web-vue/components/_utils/is-equal.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#862 fix(dropdown): fix option icon vertical align problem
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/dropdown/dropdown-option.vue
  packages/web-vue/components/dropdown/style/index.less
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/time-picker/time-picker.vue
Labels: 🔮 style

#863 fix(select): fix option problem
  packages/web-vue/components/select/hooks/use-options.ts
  packages/web-vue/components/select/interface.ts
  packages/web-vue/components/select/option.vue
Labels: 🐞 bug

#865 fix(tree): fix the connection lines are messed up
  packages/web-vue/components/tree/style/index.less
Labels: 🔮 style

#866 fix(menu): the menu indent was not displayed correctly
  packages/web-vue/components/layout/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/indent.vue
  packages/web-vue/components/menu/style/index.less
Labels: 🔮 style

#873 fix(tree-select): fix prop error
  packages/web-vue/components/button/__demo__/icon.md
  packages/web-vue/components/button/__demo__/loading.md
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/tree-select.vue
Labels: 🐞 bug

#874 feat(date-picker): dayStartOfWeek support set to 0-6
  packages/web-vue/components/_utils/date.ts
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/panels/date/index.vue
  packages/web-vue/components/date-picker/panels/week/index.vue
  packages/web-vue/components/date-picker/picker-panel.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/pickers/date-picker.tsx
  packages/web-vue/components/date-picker/pickers/week-picker.tsx
  packages/web-vue/components/date-picker/range-picker-panel.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: ✨ feature

#876 feat(tree): add property onlyCheckLeaf
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/hooks/use-checked-state.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/index.ts
Labels: ✨ feature

#867 feat(tree): enable to close expand transition animation
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
Labels: ✨ feature

#871 fix: fix popup-container problem
  packages/web-vue/components/_components/client-only.tsx
  packages/web-vue/components/_components/resize-observer-v2.vue
  packages/web-vue/components/_hooks/use-teleport-container.ts
  packages/web-vue/components/_utils/dom.ts
  packages/web-vue/components/auto-complete/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/avatar/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/drawer/__test__/index.test.ts
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/dropdown/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/layout/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/mention/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/__test__/index.test.ts
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/pagination/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/popconfirm/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/popconfirm/__test__/index.test.ts
  packages/web-vue/components/popover/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/progress/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/slider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/steps/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/time-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/timeline/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tooltip/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tooltip/__test__/index.test.ts
  packages/web-vue/components/tree-select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/trigger/__demo__/align-point.md
  packages/web-vue/components/trigger/__demo__/arrow.md
  packages/web-vue/components/trigger/__demo__/basic.md
  packages/web-vue/components/trigger/__demo__/nest.md
  packages/web-vue/components/trigger/__demo__/scroll.md
  packages/web-vue/components/trigger/__demo__/translate.md
  packages/web-vue/components/trigger/__demo__/triggers.md
  packages/web-vue/components/trigger/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/typography/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
Labels: 🐞 bug

#870 fix(avatar): fix watch warning problem
  packages/web-vue/components/avatar/avatar.vue
Labels: 🐞 bug

#877 feat(table): add summary
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/__demo__/summary.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#860 Fix Tag And Modal Bug
  packages/web-vue/components/_utils/dom.ts
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/tag/README.en-US.md
  packages/web-vue/components/tag/README.zh-CN.md
  packages/web-vue/components/tag/__demo__/size.md
  packages/web-vue/components/tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tag/tag.vue
Labels: 🐞 bug

#848 增加filednames的自定义icon功能
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/__demo__/field-names.md
  packages/web-vue/components/tree/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree/interface.ts
Labels: ✨ feature

#879 fix(affix): fix ssr problem
  packages/web-vue/components/affix/affix.vue
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
Labels: 🐞 bug

#886 fix: [select] in multiple mode no close
  packages/web-vue/components/select/select.tsx
Labels: 🐞 bug

#893 fix(select): fix fallback problem
  packages/web-vue/components/select/__demo__/fallback.md
  packages/web-vue/components/select/select.tsx
Labels: 🐞 bug
