Repository arco-design/arco-design-vue, pull requests merged in 2022-10, with the labels that each got.

#1723 fix(transfer): fix transfer scrolling
  packages/web-vue/components/transfer/style/index.less
Labels: type: 🐞 bug

#1717 Fix sizing issue for spin
  packages/web-vue/components/spin/spin.tsx
Labels: type: 🐞 bug

#1733 fix(table): fix summary row problem with table scrolling
  packages/web-vue/components/table/style/index.less
Labels: type: 🔮 style

#1682 enhance(modal): Model.open can set renderToBody
  packages/web-vue/components/modal/index.tsx
Labels: type: 🐞 bug

#1670 enhance(descriptions): 新增 tableLayout属性
  packages/web-vue/components/descriptions/README.en-US.md
  packages/web-vue/components/descriptions/README.zh-CN.md
  packages/web-vue/components/descriptions/descriptions.tsx
  packages/web-vue/components/descriptions/style/index.less
Labels: type: feature request

#1676 fix-feat-docs(notification): list style, showIcon, custom close & style
  packages/web-vue/components/notification/README.en-US.md
  packages/web-vue/components/notification/README.zh-CN.md
  packages/web-vue/components/notification/TEMPLATE.md
  packages/web-vue/components/notification/__demo__/basic.md
  packages/web-vue/components/notification/__demo__/btn.md
  packages/web-vue/components/notification/__demo__/custom-close.md
  packages/web-vue/components/notification/__demo__/position.md
  packages/web-vue/components/notification/__demo__/style.md
  packages/web-vue/components/notification/__demo__/type.md
  packages/web-vue/components/notification/__demo__/update_duration.md
  packages/web-vue/components/notification/__demo__/update_notification.md
  packages/web-vue/components/notification/index.ts
  packages/web-vue/components/notification/interface.ts
  packages/web-vue/components/notification/notification-list.tsx
  packages/web-vue/components/notification/notification.vue
  packages/web-vue/components/notification/style/index.less
Labels: type: 🐞 bug, type: docs, type: enhancement, type: feature request, type: 🔮 style

#1731 fix: selected option label in remote search
  packages/web-vue/components/select/select.tsx
Labels: type: enhancement

#1746 fix(cascader): fix multiple select problem
  packages/web-vue/components/cascader/utils.ts
Labels: type: 🐞 bug

#1770 fix(picker): fix safari style problem
  packages/web-vue/components/_components/picker/style/index.less
  packages/web-vue/components/_components/picker/style/token.less
Labels: type: 🐞 bug

#1771 enhance(cascader): enhance multi disabled
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/interface.ts
  packages/web-vue/components/cascader/utils.ts
Labels: type: enhancement

#1755 fix(progress): fix steps active error
  packages/web-vue/components/progress/steps.vue
Labels: type: enhancement

#1750 feat(pagination): Make sure to enter an integer in the input box
  packages/web-vue/components/pagination/page-jumper.vue
Labels: type: enhancement

#1480 fix(trigger): fix arrow position error
  packages/web-vue/components/trigger/trigger.tsx
Labels: type: 🐞 bug, status: invalid

#1790 chore(CONTRIBUTING.md): Replacement characters
  CONTRIBUTING.md
  CONTRIBUTING.zh-CN.md
Labels: type: docs

#1782 enhance: add instance types export
  packages/web-vue/components/cascader/index.ts
  packages/web-vue/components/descriptions/index.ts
  packages/web-vue/components/grid/index.ts
  packages/web-vue/components/index.ts
  packages/web-vue/components/overflow-list/index.ts
  packages/web-vue/components/table/index.ts
Labels: type: typescript

#1775 docs(tag): Correction of text description of tag-size
  packages/web-vue/components/tag/__demo__/size.md
Labels: type: docs

#1779 fix: fix form rule problem
  packages/web-vue/components/form/form-item.vue
Labels: type: 🐞 bug

#1778 fix: fix the problem of modal memory leak
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/drawer/__test__/index.test.ts
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/drawer/index.ts
  packages/web-vue/components/modal/index.tsx
  packages/web-vue/components/modal/modal.vue
Labels: type: 🐞 bug

#1797 fix(select): fix formatLabel problem
  packages/web-vue/components/select/select.tsx
Labels: type: 🐞 bug

#1796 fix(modal): fix modal custom zIndex problem
  packages/web-vue/components/modal/modal.vue
Labels: type: 🐞 bug

#1795 fix(table): fix stripe style problem
  packages/web-vue/components/table/style/index.less
Labels: type: 🔮 style

#1794 fix(radio): fix modelValue set undefined problem
  packages/web-vue/components/checkbox/checkbox.tsx
  packages/web-vue/components/radio/radio.tsx
Labels: type: 🐞 bug

#1774 feat(space): add split slot
  packages/web-vue/components/alert/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/avatar/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/badge/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/breadcrumb/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/button/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/carousel/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/checkbox/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/collapse/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/descriptions/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/dropdown/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/grid/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/image/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-number/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input-tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/input/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/link/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/mention/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/message/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/notification/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/page-header/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/pagination/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/popconfirm/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/popover/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/progress/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/radio/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/rate/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/result/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/skeleton/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/slider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/space/README.en-US.md
  packages/web-vue/components/space/README.zh-CN.md
  packages/web-vue/components/space/TEMPLATE.md
  packages/web-vue/components/space/__demo__/split.md
  packages/web-vue/components/space/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/space/__test__/__snapshots__/index.test.ts.snap
  packages/web-vue/components/space/space.tsx
  packages/web-vue/components/spin/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/statistic/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/steps/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/switch/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tabs/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tag/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/textarea/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tooltip/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree-select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/trigger/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/typography/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
Labels: type: feature request
