Repository arco-design/arco-design-vue, pull requests merged in 2022-01, with the labels that each got.

#513 feat(size): add global size
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/config-provider/README.en-US.md
  packages/web-vue/components/config-provider/README.zh-CN.md
  packages/web-vue/components/config-provider/config-provider.vue
  packages/web-vue/components/config-provider/context.ts
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/form/form.vue
  packages/web-vue/components/form/style/index.less
  packages/web-vue/components/image/preview-group.vue
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input-search.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/pagination/pagination.tsx
  packages/web-vue/components/progress/progress.vue
  packages/web-vue/components/select/base-select.tsx
  packages/web-vue/components/style/normalize.less
  packages/web-vue/components/switch/switch.vue
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/tag/tag.vue
  packages/web-vue/components/time-picker/time-picker.vue
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/icon/_svgs/general/outline/bar-chart.svg
  packages/web-vue/icon/_svgs/general/outline/bookmark.svg
  packages/web-vue/icon/_svgs/general/outline/computer.svg
  packages/web-vue/icon/_svgs/general/outline/layers.svg
  packages/web-vue/icon/_svgs/general/outline/relation.svg
Labels: ✨ feature

#514 fix(statistic): fix value problem
  packages/web-vue/components/statistic/countdown.vue
  packages/web-vue/components/statistic/statistic.vue
Labels: ✨ feature

#515 feat(drawer): add hide title
  packages/web-vue/components/drawer/drawer.vue
Labels: ✨ feature

#516 fix(input): fix change & attr problem
  packages/web-vue/components/input/input.tsx
Labels: 🐞 bug

#517 feat(upload): add imagePreview prop
  packages/web-vue/components/upload/__demo__/picture-card.md
  packages/web-vue/components/upload/style/index.less
  packages/web-vue/components/upload/upload-button.tsx
  packages/web-vue/components/upload/upload-list.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: ✨ feature

#518 fix(trigger): fix arrow position problem
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/trigger/utils.ts
Labels: 🐞 bug

#519 fix(table): fix resize & selection problem
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#520 feat(table): add hideExpandButtonOnEmpty prop
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#511 fix: fix init problem on windows
  .yarnrc.yml
  packages/arco-vue-scripts/copy-template.js
  packages/arco-vue-scripts/package.json
  packages/web-vue/package.json
  yarn.lock
Labels: 🐞 bug

#491 修正文档中错别字“一下”为“以下”
  packages/web-vue/components/message/README.zh-CN.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/notification/README.zh-CN.md
Labels: 📖 documentation

#502 fix(list): split invalid when bordered is false
  packages/web-vue/components/list/style/index.less
Labels: 🐞 bug, 🔮 style

#522 fix(image): the group component should collect previewProps.src first
  packages/web-vue/components/image/image.vue
Labels: 🐞 bug

#523 feat(style): add select style
  packages/web-vue/components/_components/dropdown/dropdown-option.vue
  packages/web-vue/components/_components/input-label/style/index.ts
  packages/web-vue/components/_components/input-label/style/input-label.less
  packages/web-vue/components/_components/input-label/style/token.less
  packages/web-vue/components/_components/select-view/style/index.less
  packages/web-vue/components/_components/select-view/style/index.ts
  packages/web-vue/components/_components/select-view/style/token.less
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/cascader/style/index.ts
  packages/web-vue/components/dropdown/style/index.less
  packages/web-vue/components/dropdown/style/index.ts
  packages/web-vue/components/dropdown/style/token.less
  packages/web-vue/components/index.less
  packages/web-vue/components/select/style/index.less
  packages/web-vue/components/select/style/index.ts
  packages/web-vue/components/select/style/token.less
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-operation-th.tsx
Labels: 🔮 style

#537 feat: add global notice
  packages/arco-vue-docs/app.vue
  packages/arco-vue-docs/style/index.less
Labels: 📖 documentation

#536 fix: fix style problem
  packages/web-vue/components/_components/input-label/style/index.ts
  packages/web-vue/components/_components/select-view/style/index.ts
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/form/style/index.less
  packages/web-vue/components/input/style/input.less
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/base-select.tsx
  packages/web-vue/components/steps/__demo__/dot.md
  packages/web-vue/components/steps/steps.tsx
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/textarea/textarea.vue
  packages/web-vue/components/upload/upload.tsx
Labels: 🐞 bug

#532 Correct typos "一下" to "以下"
  packages/web-vue/components/message/README.zh-CN.md
  packages/web-vue/components/message/TEMPLATE.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/TEMPLATE.md
  packages/web-vue/components/notification/README.zh-CN.md
  packages/web-vue/components/notification/TEMPLATE.md
Labels: 📖 documentation

#534 fix(statistic): fix animation problem
  packages/web-vue/components/statistic/statistic.vue
Labels: 🐞 bug

#538 fix(button): fix only-icon style
  packages/web-vue/components/button/style/index.less
Labels: 🔮 style

#543 fix(select): missing arguments when calling scrollTo
  packages/web-vue/components/_components/virtual-list/hooks/use-scroll-to.ts
  packages/web-vue/components/_components/virtual-list/interface.ts
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
  packages/web-vue/components/_hooks/use-options.tsx
Labels: 🐞 bug

#551 docs: remove duplicate lines
  packages/arco-vue-docs/docs/pro/directory.en-US.md
  packages/arco-vue-docs/docs/pro/directory.zh-CN.md
Labels: 📖 documentation

#552 fix(input): fix input-search & input-number problem
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-number/style/index.less
  packages/web-vue/components/input/input-search.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/input/style/group.less
  packages/web-vue/components/input/style/password.less
  packages/web-vue/components/input/style/search.less
  packages/web-vue/components/input/style/size.less
Labels: 🐞 bug

#563 fix(time-column): fix types
  packages/web-vue/components/time-picker/time-column.vue
Labels: 🐞 bug

#557 feat(select): chore loading state
  packages/web-vue/components/_components/dropdown/dropdown-panel.vue
  packages/web-vue/components/_components/dropdown/style/index.less
  packages/web-vue/components/select/__demo__/loading.md
  packages/web-vue/components/select/base-select.tsx
Labels: 💎 enhancement

#558 feat(cascader): add loading state
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/TEMPLATE.md
  packages/web-vue/components/cascader/__demo__/loading.md
  packages/web-vue/components/cascader/cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/style/index.less
Labels: ✨ feature

#560 fix(input): fix background-color error in dark mode
  packages/web-vue/components/input/style/input.less
Labels: 🔮 style

#567 fix(button): fix button group align problem
  packages/web-vue/components/button/style/index.less
Labels: 🔮 style

#569 perf(select): perf select used with checkbox-group
  packages/web-vue/components/_components/dropdown/dropdown-option.vue
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/checkbox/checkbox.vue
  packages/web-vue/components/radio/radio.vue
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-operation-th.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/transfer/transfer-list-item.tsx
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/tree/base-node.vue
Labels: 💎 enhancement

#570 fix(tag): fix checkable class name error
  packages/web-vue/components/tag/tag.vue
Labels: 🔮 style

#574 feat(icon): add icon & icon-font component
  packages/arco-vue-docs/pages/icon/README.en-US.md
  packages/arco-vue-docs/pages/icon/README.zh-CN.md
  packages/arco-vue-docs/pages/icon/__demo__/basic.md
  packages/arco-vue-docs/pages/icon/__demo__/icon-font.md
  packages/arco-vue-docs/pages/icon/icon-demo.vue
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/icon-component/add-from-icon-font-cn.tsx
  packages/web-vue/components/icon-component/icon.vue
  packages/web-vue/components/icon-component/index.ts
  packages/web-vue/components/icon-component/style/index.ts
  packages/web-vue/components/index.ts
Labels: ✨ feature

#575 feat(table): add sorter boolean support
  packages/web-vue/components/table/__demo__/sort.md
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#577 feat(modal): add escToClose support
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/interface.ts
  packages/web-vue/components/modal/modal.vue
Labels: ✨ feature

#579 fix(date-picker): fix the event params of date-picker
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/pickers/date-picker.tsx
  packages/web-vue/components/date-picker/pickers/month-picker.tsx
  packages/web-vue/components/date-picker/pickers/quarter-picker.tsx
  packages/web-vue/components/date-picker/pickers/week-picker.tsx
  packages/web-vue/components/date-picker/pickers/year-picker.tsx
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/time-picker/utils/index.ts
Labels: 🐞 bug

#581 fix(grid): fix install name
  packages/web-vue/components/grid/__demo__/grid.md
  packages/web-vue/components/grid/index.ts
Labels: 🐞 bug

#630 perf(table): button not trigger row-click
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: 💎 enhancement

#628 feat(modal): add before events
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/modal.vue
Labels: ✨ feature

#627 fix(cascader): fix check-strictly mode problem in search
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
Labels: 🐞 bug

#625 feat(input): input-search support button slots
  packages/web-vue/components/input/README.en-US.md
  packages/web-vue/components/input/README.zh-CN.md
  packages/web-vue/components/input/TEMPLATE.md
  packages/web-vue/components/input/__demo__/search-button.md
  packages/web-vue/components/input/__demo__/status.md
  packages/web-vue/components/input/input-search.tsx
Labels: ✨ feature

#622 feat: add feedback icon
  packages/web-vue/components/_components/feedback-icon.vue
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/_components/select-view/style/index.less
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/TEMPLATE.md
  packages/web-vue/components/form/__demo__/status.md
  packages/web-vue/components/form/form-item.tsx
  packages/web-vue/components/form/style/status.less
  packages/web-vue/components/input-number/style/index.less
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/input/style/input.less
  packages/web-vue/components/input/style/token.less
Labels: ✨ feature

#619 feat(table): add drag support
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/__demo__/column-resize.md
  packages/web-vue/components/table/__demo__/custom-dom.md
  packages/web-vue/components/table/__demo__/drag-handle.md
  packages/web-vue/components/table/__demo__/drag-row.md
  packages/web-vue/components/table/hooks/use-column-resize.ts
  packages/web-vue/components/table/hooks/use-drag.ts
  packages/web-vue/components/table/index.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/style/token.less
  packages/web-vue/components/table/table-col-group.vue
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-tbody.tsx
  packages/web-vue/components/table/table-tbody.vue
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table-tr.tsx
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: ✨ feature

#608 chore(dropdown): use context to refactor dropdown
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/TEMPLATE.md
  packages/web-vue/components/dropdown/__demo__/basic.md
  packages/web-vue/components/dropdown/__demo__/button.md
  packages/web-vue/components/dropdown/__demo__/submenu.md
  packages/web-vue/components/dropdown/__demo__/trigger.md
  packages/web-vue/components/dropdown/context.ts
  packages/web-vue/components/dropdown/dropdown-button.vue
  packages/web-vue/components/dropdown/dropdown-group.ts
  packages/web-vue/components/dropdown/dropdown-group.vue
  packages/web-vue/components/dropdown/dropdown-option.ts
  packages/web-vue/components/dropdown/dropdown-option.vue
  packages/web-vue/components/dropdown/dropdown-panel.vue
  packages/web-vue/components/dropdown/dropdown-submenu.ts
  packages/web-vue/components/dropdown/dropdown-submenu.vue
  packages/web-vue/components/dropdown/dropdown.tsx
  packages/web-vue/components/dropdown/dropdown.vue
  packages/web-vue/components/dropdown/index.ts
  packages/web-vue/components/index.ts
  packages/web-vue/components/trigger/trigger.tsx
Labels: ✨ feature

#588 fix(input): fix input-group style problem
  packages/web-vue/components/input/style/group.less
Labels: 🔮 style

#591 fix(typography): move slots.default() to render
  packages/web-vue/components/typography/base.tsx
  packages/web-vue/components/typography/interface.ts
Labels: 🐞 bug

#623 docs: add pinia docs
  packages/arco-vue-docs/docs/pro/state-management-pinia.en-US.md
  packages/arco-vue-docs/docs/pro/state-management-pinia.zh-CN.md
  packages/arco-vue-docs/docs/pro/state-management.en-US.md
  packages/arco-vue-docs/docs/pro/state-management.zh-CN.md
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
Labels: 📖 documentation

#607 feat(split): attributes `min` and `max` support setting pixel values
  packages/web-vue/components/split/README.en-US.md
  packages/web-vue/components/split/README.zh-CN.md
  packages/web-vue/components/split/__demo__/basic.md
  packages/web-vue/components/split/__demo__/nested.md
  packages/web-vue/components/split/interface.ts
  packages/web-vue/components/split/split.vue
Labels: 💎 enhancement

#612 fix(date-picker): the time should not be concatenated when the time i…
  packages/web-vue/components/date-picker/hooks/use-is-disabled-date.ts
  packages/web-vue/components/date-picker/picker.vue
Labels: 🐞 bug

#631 feat(date-picker): add property `value-format`
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/hooks/use-format.ts
  packages/web-vue/components/date-picker/hooks/use-value-format.ts
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/pickers/date-picker.tsx
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/time-picker/utils/index.ts
Labels: ✨ feature

#633 feat(date-picker): do not open the popup when clear
  packages/web-vue/components/_components/picker/input-range.vue
  packages/web-vue/components/_components/picker/input.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: 🐞 bug

#632 feat(typography): add property `copyDelay`
  packages/web-vue/components/typography/README.en-US.md
  packages/web-vue/components/typography/README.zh-CN.md
  packages/web-vue/components/typography/base.tsx
  packages/web-vue/components/typography/interface.ts
Labels: ✨ feature

#634 feat(select): add icon slots
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/base-select.tsx
Labels: ✨ feature

#635 fix(message): fix message type problem
  packages/web-vue/components/message/message-list.tsx
  packages/web-vue/components/message/message.vue
  packages/web-vue/components/modal/style/index.ts
Labels: 🐞 bug

#636 fix(button): fix button href type text align
  packages/web-vue/components/button/style/index.less
Labels: 🔮 style

#637 fix(dropdown): add dropdown props
  packages/arco-vue-docs-navbar/package.json
  packages/arco-vue-docs-navbar/src/index.less
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/TEMPLATE.md
  packages/web-vue/components/dropdown/__demo__/button.md
  packages/web-vue/components/dropdown/dropdown-button.vue
  packages/web-vue/components/dropdown/dropdown.vue
  yarn.lock
Labels: 🐞 bug

#640 fix(input): fix input-group style
  packages/web-vue/components/input/style/group.less
  packages/web-vue/components/input/style/index.less
Labels: 🔮 style

#641 fix(table): fix lazy load problem
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#642 fix(icon): add fill attr
  packages/web-vue/components/icon-component/icon.vue
Labels: 🔮 style

#643 fix(date-picker): `headerValue` reporting error in `vue 3.2.28`
  packages/web-vue/components/date-picker/picker.vue
Labels: 🐞 bug
