Repository arco-design/arco-design-vue, pull requests merged in 2022-08, with the labels that each got.

#1488 fix: fix accept file util
  packages/web-vue/components/upload/utils.tsx
Labels: 🐞 bug, 💎 enhancement

#1483 style(cascader): fix dropdown panel style
  packages/web-vue/components/cascader/style/index.less
Labels: 🐞 bug, 🔮 style

#1421 feat(DatePicker): add range picker header label click and normal pick…
  packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/date-picker/hooks/use-header-value.ts
  packages/web-vue/components/date-picker/hooks/use-panel-span.ts
  packages/web-vue/components/date-picker/hooks/use-range-header-value.ts
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/panels/header.vue
  packages/web-vue/components/date-picker/picker-panel.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker-panel.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: ✨ feature

#1490 feat(icon): support rotate prop and docs filter bar
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/pages/icon/__demo__/basic.md
  packages/arco-vue-docs/pages/icon/__demo__/icon-font.md
  packages/arco-vue-docs/pages/icon/__demo__/spin.md
  packages/arco-vue-docs/pages/icon/icon-demo.vue
  packages/arco-vue-docs/pages/icon/style.less
  packages/arco-vue-docs/utils/strings.ts
  packages/arco-vue-scripts/src/scripts/icongen/svgo.config.ts
  packages/arco-vue-scripts/src/scripts/icongen/vue-template.ts
  packages/web-vue/components/icon-component/add-from-icon-font-cn.tsx
  packages/web-vue/components/icon-component/icon.vue
Labels: ✨ feature

#1473 feat(divider): support line style and margin
  packages/web-vue/components/divider/README.en-US.md
  packages/web-vue/components/divider/README.zh-CN.md
  packages/web-vue/components/divider/__demo__/basic.md
  packages/web-vue/components/divider/__demo__/with-text.md
  packages/web-vue/components/divider/divider.tsx
Labels: ✨ feature

#1529 enhance(trigger): enhance KeepAlive
  packages/web-vue/components/trigger/trigger.tsx
Labels: 🐞 bug

#1516 fix: fix click loading button in form can trigger submit
  packages/web-vue/components/button/button.vue
Labels: 💎 enhancement

#1513 fix(time-picker): remove the default value of the size prop
  packages/web-vue/components/form/__demo__/validation.md
  packages/web-vue/components/time-picker/time-picker.vue
Labels: 🐞 bug

#1533 fix(spin): fix z-index problem
  packages/web-vue/components/spin/style/index.less
Labels: 🐞 bug

#1562 fix: DatePicker quick select from month bug
  packages/web-vue/components/date-picker/picker.vue
Labels: type: 🐞 bug

#1576 enhance: matchMedia compatible with safari 13
  packages/web-vue/components/_utils/responsive-observe.ts
Labels: type: enhancement

#1577 fix(image): fix preview close button icon position problem
  packages/web-vue/components/image/style/preview.less
Labels: type: 🔮 style

#1578 enhance(date-picker): correct order on select
  packages/web-vue/components/date-picker/range-picker.vue
Labels: type: enhancement

#1579 fix(pagination): fix the problem that the display content is compressed
  packages/web-vue/components/pagination/style/index.less
Labels: type: 🔮 style
