Repository arco-design/arco-design-vue, pull requests merged in 2022-02, with the labels that each got.

#655 fix(trigger): fix auto-fit arrow position
  packages/web-vue/components/trigger/utils.ts
Labels: 💎 enhancement

#656 fix(switch): fix turn on style problem
  packages/web-vue/components/switch/style/index.less
Labels: 🔮 style

#659 fix(transfer): use option label to search
  packages/web-vue/components/transfer/transfer-view.vue
Labels: 🐞 bug

#664 perf(input): add input attrs
  packages/web-vue/components/_utils/constant.ts
Labels: 💎 enhancement

#677 fix(image): the Tootip of Action has a wrong `zindex`
  packages/web-vue/components/image/style/preview.less
Labels: 🐞 bug

#671 docs: jump link correction
  packages/arco-vue-docs/docs/pro/mock.en-US.md
  packages/arco-vue-docs/docs/pro/mock.zh-CN.md
Labels: 📖 documentation

#673 feat(modal): add title align prop
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/modal/style/index.less
Labels: ✨ feature

#674 fix(tooltip): fix lost trigger style problem
  packages/web-vue/components/tooltip/style/index.ts
Labels: 🐞 bug

#676 fix(icon): fix some icon color problem
  packages/web-vue/icon/_svgs/general/outline/bar-chart.svg
  packages/web-vue/icon/_svgs/general/outline/bookmark.svg
  packages/web-vue/icon/_svgs/general/outline/computer.svg
  packages/web-vue/icon/_svgs/general/outline/layers.svg
  packages/web-vue/icon/_svgs/general/outline/relation.svg
Labels: 🔮 style

#678 fix(image): wrong direction of rotation
  packages/web-vue/components/image/preview.vue
Labels: 🐞 bug

#691 docs: add vue pro permission control docs
  packages/arco-vue-docs/docs/pro/permission.en-US.md
  packages/arco-vue-docs/docs/pro/permission.zh-CN.md
  packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
  packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
Labels: 📖 documentation

#700 feat(menu): support responsive breakpoint
  packages/web-vue/components/_hooks/use-responsive.ts
  packages/web-vue/components/layout/sider.vue
  packages/web-vue/components/menu/README.en-US.md
  packages/web-vue/components/menu/README.zh-CN.md
  packages/web-vue/components/menu/TEMPLATE.md
  packages/web-vue/components/menu/__demo__/breakpoint.md
  packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/menu/interface.ts
Labels: ✨ feature

#694 feat(script-docgen): add component desc
  packages/arco-vue-scripts/src/scripts/docgen/index.ts
Labels: feat: scripts

#701 fix(cascader): fix check-strictly problem
  packages/web-vue/components/cascader/__demo__/check-strictly.md
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/checkbox/checkbox.vue
Labels: 🐞 bug

#705 fix(message): fix destroy problem
  packages/web-vue/components/message/index.ts
  packages/web-vue/components/notification/index.ts
Labels: 🐞 bug

#706 fix(upload): only generate image when image type
  packages/web-vue/components/upload/upload.tsx
  packages/web-vue/components/upload/utils.tsx
Labels: 🐞 bug

#710 feat(tree): add icon slot
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/TEMPLATE.md
  packages/web-vue/components/tree/__demo__/node-icon.md
  packages/web-vue/components/tree/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree/base-node.vue
  packages/web-vue/components/tree/context.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
Labels: ✨ feature

#711 fix(virtual-list): view not update & itemHeight is wrong
  packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx
  packages/web-vue/components/_components/virtual-list/interface.ts
  packages/web-vue/components/_components/virtual-list/utils/index.ts
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#715 fix(upload): fix error when using slot `upload-item`
  packages/web-vue/components/upload/upload-list.tsx
Labels: 🐞 bug

#727 fix(cascader): fix option update problem
  packages/web-vue/components/cascader/cascader.vue
Labels: 🐞 bug

#728 feat(select): add search delay
  packages/web-vue/components/_hooks/use-index.ts
  packages/web-vue/components/grid/grid-item.vue
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/TEMPLATE.md
  packages/web-vue/components/select/__demo__/remote.md
  packages/web-vue/components/select/hooks/use-options.ts
  packages/web-vue/components/select/hooks/use-select.ts
  packages/web-vue/components/select/option.vue
  packages/web-vue/components/select/select.tsx
Labels: ✨ feature

#729 feat(cascader): add search delay
  packages/web-vue/components/_hooks/use-input.ts
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/cascader-option.tsx
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/context.ts
  packages/web-vue/components/cascader/utils.ts
Labels: ✨ feature

#730 perf(list): always render spin; support any child element
  packages/web-vue/components/_utils/vue-utils.ts
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/space/space.tsx
Labels: 💎 enhancement

#731 feat(trigger): add show/hide event
  packages/web-vue/components/trigger/trigger.tsx
Labels: ✨ feature

#732 chore(trigger): add wrapper div for support transform animate
  packages/web-vue/components/_components/resize-observer-v2.vue
  packages/web-vue/components/trigger/__demo__/arrow.md
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/trigger/utils.ts
Labels: 💎 enhancement

#734 fix(table): fix table-column nest problem
  packages/web-vue/components/table/utils.ts
Labels: 🐞 bug

#735 feat(table): add span-all prop
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/__demo__/span.md
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#736 fix(pagination): fix style error in safari
  packages/web-vue/components/pagination/style/index.less
Labels: 🔮 style

#737 perf(modal): perf click mask to close
  packages/web-vue/components/modal/index.tsx
  packages/web-vue/components/modal/modal.vue
Labels: 💎 enhancement

#738 perf(form): nowrap when auto-label-width
  packages/web-vue/components/form/form.vue
  packages/web-vue/components/form/style/index.less
Labels: 💎 enhancement

#724 feat(form): validated error info add label props
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/form-item.vue
  packages/web-vue/components/form/interface.ts
Labels: ✨ feature

#743 perf(input): support value null
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/select/select.tsx
Labels: 💎 enhancement

#744 fix(transfer): fix style problem
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/list/style/index.less
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/transfer/transfer.vue
Labels: 🔮 style
