Repository arco-design/arco-design-vue, pull requests merged in 2022-11, with the labels that each got.

#1820 fix: fix cursor hook
  packages/web-vue/components/_hooks/use-cursor.ts
Labels: type: 🐞 bug

#1812 fix(table): fix param when rowClass as function
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#1822 fix(pagination): Eliminate page jumper warnings (#1814)
  packages/web-vue/components/pagination/page-jumper.vue
Labels: type: 🐞 bug

#1834 fix(virtual): fix key problem
  packages/web-vue/components/_components/virtual-list-v2/virtual-list-item.tsx
  packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue
  packages/web-vue/components/radio/radio-group.tsx
Labels: type: 🐞 bug

#1835 enhance(icon): replace lark icon
  packages/web-vue/icon/_svgs/logo/color/lark-color.svg
Labels: type: enhancement

#1818 fix(date-picker): fix prop error
  packages/web-vue/components/date-picker/pickers/date-picker.tsx
Labels: type: 🐞 bug

#1836 fix(input-tag): fix delete problem
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: type: 🐞 bug

#1849 fix(table): fix row-selection problem
  packages/web-vue/components/table/__demo__/row-selection.md
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/table-operation-th.tsx
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#1842 feat(tree-select): Let go of some tree component slots
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: docs

#1864 fix(space): fix split margin
  packages/web-vue/components/space/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/space/space.tsx
Labels: type: 🐞 bug

#1859 fix(switch): fix before change value and style token
  packages/web-vue/components/switch/README.en-US.md
  packages/web-vue/components/switch/README.zh-CN.md
  packages/web-vue/components/switch/style/token.less
  packages/web-vue/components/switch/switch.vue
Labels: type: 🐞 bug

#1872 enhance(tree-select): replace virtual scrollbar
  packages/web-vue/components/_hooks/use-scrollbar.ts
  packages/web-vue/components/tree-select/panel.tsx
  packages/web-vue/components/tree-select/style/index.less
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: feature request

#1841 feat(message): clear the timer when the mouse moves in
  packages/web-vue/components/message/README.en-US.md
  packages/web-vue/components/message/README.zh-CN.md
  packages/web-vue/components/message/interface.ts
  packages/web-vue/components/message/message-list.tsx
  packages/web-vue/components/message/message.vue
Labels: type: feature request

#1873 feat(transfer): support content slot
  packages/web-vue/components/transfer/README.en-US.md
  packages/web-vue/components/transfer/README.zh-CN.md
  packages/web-vue/components/transfer/TEMPLATE.md
  packages/web-vue/components/transfer/__demo__/tree.md
  packages/web-vue/components/transfer/style/index.less
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/transfer/transfer.vue
Labels: type: feature request

#1845 enhance(transfer): can hide select all checkbox
  packages/web-vue/components/transfer/README.en-US.md
  packages/web-vue/components/transfer/README.zh-CN.md
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/transfer/transfer.vue
Labels: type: feature request

#1857 enhance(upload): add some common file type
  packages/web-vue/components/upload/upload-list-item.tsx
Labels: type: enhancement

#1847 fix(date-picker): year range can't skip by 10 year
  packages/web-vue/components/date-picker/range-picker.vue
Labels: type: 🐞 bug

#1890 fix(locale): fix ja-jp problem
  packages/web-vue/components/locale/lang/ja-jp.ts
Labels: type: 🐞 bug

#1888 enhance(doc): replace union type
  packages/web-vue/components/anchor/README.en-US.md
  packages/web-vue/components/anchor/README.zh-CN.md
  packages/web-vue/components/anchor/anchor.vue
  packages/web-vue/components/checkbox/README.en-US.md
  packages/web-vue/components/checkbox/README.zh-CN.md
  packages/web-vue/components/checkbox/checkbox-group.tsx
  packages/web-vue/components/checkbox/checkbox.tsx
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/dropdown.vue
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/form.vue
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/radio/README.en-US.md
  packages/web-vue/components/radio/README.zh-CN.md
  packages/web-vue/components/radio/radio-group.tsx
  packages/web-vue/components/radio/radio.tsx
  packages/web-vue/components/switch/README.en-US.md
  packages/web-vue/components/switch/README.zh-CN.md
  packages/web-vue/components/switch/switch.vue
  packages/web-vue/components/tabs/README.en-US.md
  packages/web-vue/components/tabs/README.zh-CN.md
  packages/web-vue/components/tabs/tabs.tsx
Labels: type: docs

#1885 enhance(tree-select): update the type of trigger-props
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/interface.ts
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: typescript

#1879 fix(table):Make sure that deleting the data table updates the rendering correctly
  packages/web-vue/components/pagination/__test__/index.test.ts
  packages/web-vue/components/pagination/__test__/index.test.tsx
  packages/web-vue/components/pagination/pagination.tsx
  packages/web-vue/components/table/__test__/index.test.ts
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug
