Repository arco-design/arco-design-vue, pull requests merged in 2022-12, with the labels that each got.

#1901 fix(carousel): transparent background images should be masked
  packages/web-vue/components/carousel/style/index.less
Labels: type: 🐞 bug

#1905 fix(divider): 指定 size 属性时，style 生成的样式错误
  packages/web-vue/components/divider/divider.tsx
Labels: type: 🐞 bug

#1912 fix(input): fix clear problem
  packages/web-vue/components/input/input.tsx
Labels: type: 🐞 bug

#1913 fix(table): fix thead scroll problem
  packages/web-vue/components/scrollbar/scrollbar.vue
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#1925 fix(docs): typo
  packages/web-vue/components/drawer/__demo__/async.md
  packages/web-vue/components/drawer/__demo__/basic.md
  packages/web-vue/components/drawer/__demo__/custom.md
  packages/web-vue/components/drawer/__demo__/nested.md
  packages/web-vue/components/drawer/__demo__/popup-container.md
  packages/web-vue/components/modal/__demo__/async.md
  packages/web-vue/components/modal/__demo__/basic.md
  packages/web-vue/components/modal/__demo__/custom.md
  packages/web-vue/components/modal/__demo__/draggable.md
  packages/web-vue/components/modal/__demo__/fullscreen.md
  packages/web-vue/components/modal/__demo__/width.md
Labels: type: docs

#1810 feat(avatar): add custom image url path
  packages/web-vue/components/avatar/README.en-US.md
  packages/web-vue/components/avatar/README.zh-CN.md
  packages/web-vue/components/avatar/TEMPLATE.md
  packages/web-vue/components/avatar/__demo__/image-url.md
  packages/web-vue/components/avatar/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/avatar/avatar.vue
  packages/web-vue/components/avatar/style/index.less
Labels: type: feature request

#1909 feat(scrollbar): add scrollbar methods
  packages/web-vue/components/scrollbar/README.en-US.md
  packages/web-vue/components/scrollbar/README.zh-CN.md
  packages/web-vue/components/scrollbar/scrollbar.vue
Labels: type: feature request

#1809 feat(auto-complete): add focus and blur method
  packages/web-vue/components/auto-complete/auto-complete.tsx
Labels: type: feature request

#1929 fix(list): fix scrollbar props problem
  packages/web-vue/components/list/__demo__/scroll.md
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/table/style/index.less
Labels: type: 🐞 bug

#1928 fix: validateStatus not work in datepicker
  packages/web-vue/components/form/style/status.less
Labels: type: 🐞 bug, type: 🔮 style

#1893 feat(table): `change` event adds parameter `currentDataSource`
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/__demo__/filter.md
  packages/web-vue/components/table/__demo__/sort.md
  packages/web-vue/components/table/__test__/index.test.ts
  packages/web-vue/components/table/table.tsx
Labels: type: feature request

#1975 fix(switch):switch类型为line,size为small,checked状态没有特定的样式
  packages/web-vue/components/switch/style/index.less
Labels: type: 🔮 style

#1971 fix(badge): 修改badge.tsx中徽标的状态类型
  packages/web-vue/components/badge/badge.tsx
Labels: type: docs

#1988 fix(tabs): fix size problem
  packages/web-vue/components/tabs/__demo__/type.md
  packages/web-vue/components/tabs/style/index.less
  packages/web-vue/components/tabs/style/token.less
Labels: type: 🔮 style

#1970 fix(List): grid list does not need scroll bar
  packages/web-vue/components/list/style/index.less
Labels: type: 🐞 bug

#1965 fix(DatePicker): fix issues in i18n
  packages/web-vue/components/date-picker/panels/week-list.vue
Labels: type: 🐞 bug

#1990 fix(input): fix change event problem
  packages/web-vue/components/input/input.tsx
Labels: type: 🐞 bug

#1964 docs(input): typo
  packages/web-vue/components/input/input.tsx
Labels: type: docs

#2005 style: Select show arrow icon
  packages/web-vue/components/_components/select-view/select-view.tsx
  packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree-select/__test__/__snapshots__/demo.test.ts.snap
Labels: type: 🔮 style

#2010 feat(upload): add upload method
  packages/web-vue/components/upload/upload.tsx
Labels: type: feature request

#1995 fix(Typography): Fixed ellipsis prop invalidation when parent container is set to white-space: nowrap
  packages/web-vue/components/typography/utils/measure.tsx
Labels: type: 🐞 bug

#2003 chore: add preview yml
  .github/workflows/deploy-site-preview.yml
  package.json
  packages/arco-vue-scripts/package.json
  packages/arco-vue-scripts/src/configs/vite.site.prod.ts
  packages/arco-vue-scripts/src/index.ts
  packages/arco-vue-scripts/src/scripts/test/screentshot.ts
  packages/arco-vue-scripts/tsconfig.json
  packages/web-vue/.gitignore
  packages/web-vue/package.json
  yarn.lock
Labels: type: chore

#2008 feat: add es locale
  packages/web-vue/components/locale/lang/es-es.ts
Labels: type: feature request

#2007 fix: upload filter files error
  packages/web-vue/components/upload/utils.ts
Labels: type: 🐞 bug

#1992 fix(image-preview): the image id may not be collected and cause previ…
  packages/web-vue/components/image/preview-group.vue
Labels: type: 🐞 bug

#1942 fix(input): 修复input组件word-length计算字符的长度不会被max-length限制
  packages/web-vue/components/input/input.tsx
Labels: type: 🐞 bug

#1940 fix(checkbox): set to an empty array when checkbox-group modevalue is…
  packages/web-vue/components/checkbox/checkbox-group.tsx
Labels: type: 🐞 bug

#2013 fix(mention): fix enter problem
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/select/hooks/use-select.ts
Labels: type: 🐞 bug

#2011 feat: add locale
  packages/arco-vue-docs/docs/i18n.en-US.md
  packages/arco-vue-docs/docs/i18n.zh-CN.md
  packages/web-vue/components/config-provider/__demo__/basic.md
  packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/locale/lang/ar-eg.ts
  packages/web-vue/components/locale/lang/de-de.ts
  packages/web-vue/components/locale/lang/es-es.ts
  packages/web-vue/components/locale/lang/fr-fr.ts
  packages/web-vue/components/locale/lang/id-id.ts
  packages/web-vue/components/locale/lang/it-it.ts
  packages/web-vue/components/locale/lang/ko-kr.ts
  packages/web-vue/components/locale/lang/ms-my.ts
  packages/web-vue/components/locale/lang/th-th.ts
Labels: type: feature request

#1938 fix(table): only the operation column fixed still has shadow
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#1997 feat: DatePicker and TimePicker supports prefix slots
  packages/web-vue/components/_components/picker/input-range.vue
  packages/web-vue/components/_components/picker/input.vue
  packages/web-vue/components/_components/picker/style/index.less
  packages/web-vue/components/_components/picker/style/token.less
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/__demo__/prefix.md
  packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/time-picker/README.en-US.md
  packages/web-vue/components/time-picker/README.zh-CN.md
  packages/web-vue/components/time-picker/__demo__/prefix.md
  packages/web-vue/components/time-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/time-picker/time-picker.vue
Labels: type: feature request

#2009 feat(message): add normal type
  packages/web-vue/components/alert/__demo__/type.md
  packages/web-vue/components/alert/alert.vue
  packages/web-vue/components/alert/style/index.less
  packages/web-vue/components/alert/style/token.less
  packages/web-vue/components/message/__demo__/type.md
  packages/web-vue/components/message/index.ts
  packages/web-vue/components/message/interface.ts
  packages/web-vue/components/message/message.vue
Labels: type: feature request
