Repository arco-design/arco-design-vue, pull requests merged in 2022-04, with the labels that each got.

#889 fix: icons are not aligned with text
  packages/web-vue/components/menu/style/index.less
Labels: 🔮 style

#917 fix(virtual-list): visibleCount is now calculated from the minItemheight
  packages/web-vue-storybook/stories/components/virtual-list.vue
  packages/web-vue/components/_components/virtual-list/hooks/use-item-height.ts
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
Labels: 🐞 bug

#894 feat(tree-select): add property fallback-option
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/TEMPLATE.md
  packages/web-vue/components/tree-select/__demo__/fallback.md
  packages/web-vue/components/tree-select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree-select/interface.ts
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/interface.ts
Labels: ✨ feature

#915 fix(typography): copy does not work
  packages/web-vue/components/typography/base.tsx
  packages/web-vue/components/typography/interface.ts
Labels: 🐞 bug

#907 fix(upload): fix onButtonClick prop problem
  packages/web-vue/components/upload/upload.tsx
Labels: 🐞 bug

#916 fix(tree-select): null should not be displayed
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
Labels: 🐞 bug

#908 fix(mention): fix v-model error
  packages/web-vue/components/mention/__demo__/basic.md
  packages/web-vue/components/mention/mention.tsx
Labels: 🐞 bug

#909 fix(input-number): fix change mode problem
  packages/web-vue/components/input-number/input-number.tsx
Labels: 🐞 bug

#910 feat(input-tag): add fieldNames
  packages/web-vue/components/_utils/types.ts
  packages/web-vue/components/input-tag/README.en-US.md
  packages/web-vue/components/input-tag/README.zh-CN.md
  packages/web-vue/components/input-tag/__demo__/size.md
  packages/web-vue/components/input-tag/index.ts
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input-tag/interface.ts
  packages/web-vue/components/input-tag/utils.ts
  packages/web-vue/components/tag/index.ts
  packages/web-vue/components/tag/interface.ts
Labels: ✨ feature

#918 fix(modal): fix base mode problem
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/modal/style/index.less
Labels: 🐞 bug

#919 feat(form): add label component
  packages/web-vue/components/form/README.en-US.md
  packages/web-vue/components/form/README.zh-CN.md
  packages/web-vue/components/form/form-item-label.vue
  packages/web-vue/components/form/form-item.vue
  packages/web-vue/components/form/style/index.less
Labels: ✨ feature

#920 feat(table): add selectAll
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#925 fix(mention): fix dev warning problem
  packages/web-vue/components/select/hooks/use-options.ts
Labels: 🐞 bug

#926 fix(table): fix virtual-list use with scroll
  packages/web-vue/components/_components/virtual-list/filler.vue
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#928 fix(menu): the line-height of icon is wrong
  packages/web-vue/components/menu/style/index.less
Labels: 🔮 style

#939 fix(tree-select): the event change has wrong params when label-in-value is true
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree-select/tree-select.vue
Labels: 🐞 bug

#949 feat(menu): support set the maximum height of popover
  packages/web-vue/components/menu/README.en-US.md
  packages/web-vue/components/menu/README.zh-CN.md
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/menu/context.ts
  packages/web-vue/components/menu/interface.ts
  packages/web-vue/components/menu/sub-menu-pop.vue
  packages/web-vue/components/menu/sub-menu.tsx
Labels: ✨ feature

#944 feat(upload): add slots and method
  packages/web-vue/components/upload/context.ts
  packages/web-vue/components/upload/index.ts
  packages/web-vue/components/upload/interfaces.ts
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload-list.tsx
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload-progress.tsx
  packages/web-vue/components/upload/upload.tsx
  packages/web-vue/components/upload/utils.tsx
Labels: 💎 enhancement, ✨ feature

#945 perf(modal): perf body scroll judgment method
  packages/web-vue/components/_hooks/use-overflow.ts
  packages/web-vue/components/_utils/dom.ts
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/modal/style/index.less
Labels: 🐞 bug

#948 feat(table): add slots
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/__demo__/filter.md
  packages/web-vue/components/table/__demo__/summary.md
  packages/web-vue/components/table/__demo__/virtual-list.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/hooks/use-column-resize.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/style/token.less
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-operation-th.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#951 feat(input): modify clear event
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-number/style/index.less
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/input/style/group.less
  packages/web-vue/components/input/style/index.less
  packages/web-vue/components/mention/mention.tsx
  packages/web-vue/components/textarea/textarea.vue
Labels: ✨ feature

#952 feat(cascader): add empty slot
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/base-cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-panel.vue
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/index.ts
  packages/web-vue/components/cascader/utils.ts
  packages/web-vue/components/index.ts
  packages/web-vue/components/select/hooks/use-options.ts
Labels: ✨ feature

#953 fix(image): fix footer style
  packages/web-vue/components/image/image.vue
  packages/web-vue/components/image/style/image.less
Labels: 🔮 style

#954 feat(pagination): add slots
  packages/web-vue/components/pagination/page-jumper.vue
  packages/web-vue/components/pagination/pagination.tsx
  packages/web-vue/components/pagination/style/index.less
Labels: 💎 enhancement, ✨ feature

#959 refactor: make nested step can have correct index
  packages/web-vue/components/steps/__test__/index.test.ts
  packages/web-vue/components/steps/context.ts
  packages/web-vue/components/steps/step.vue
  packages/web-vue/components/steps/steps.vue
Labels: 🐞 bug

#977 chore: export interface of tree/tree-select/date-picker
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/TEMPLATE.md
  packages/web-vue/components/date-picker/index.ts
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/index.ts
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/hooks/use-filter-tree-node.ts
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
  packages/web-vue/components/tree-select/interface.ts
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/hooks/use-tree-data.ts
  packages/web-vue/components/tree/index.ts
  packages/web-vue/components/tree/interface.ts
  packages/web-vue/components/tree/tree.vue
  packages/web-vue/components/tree/utils/tree-data.ts
  packages/web-vue/components/typography/index.ts
Labels: typescript

#963 fix: checkbox indeterminate status error on cascader multiple mode
  packages/web-vue/components/cascader/utils.ts
Labels: 🐞 bug

#968 fix(modal): fix body scroll problem
  packages/web-vue/components/_utils/dom.ts
  packages/web-vue/components/rate/style/index.less
Labels: 🐞 bug

#969 perf(table): render titleSlot first
  packages/web-vue/components/table/table-th.tsx
Labels: 💎 enhancement

#966 fix(menu): scroll into view done not take effect
  packages/web-vue/components/_hooks/use-is-mounted.ts
  packages/web-vue/components/menu/item.tsx
Labels: 🐞 bug

#985 feat(modal): add animation-name
  packages/web-vue/components/card/style/index.less
  packages/web-vue/components/card/style/token.less
  packages/web-vue/components/modal/modal.vue
Labels: ✨ feature

#984 fix(pagination): add padding style
  packages/web-vue/components/pagination/style/index.less
  packages/web-vue/components/pagination/style/token.less
  packages/web-vue/components/textarea/textarea.vue
Labels: 🔮 style

#980 fix(typography): fix the warning of slot.default
  packages/web-vue/components/typography/base.tsx
Labels: 🐞 bug

#967 feat: button group props
  packages/web-vue/components/button/README.en-US.md
  packages/web-vue/components/button/README.zh-CN.md
  packages/web-vue/components/button/__demo__/group.md
  packages/web-vue/components/button/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/button/button-group.vue
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/button/constants.ts
  packages/web-vue/components/button/context.ts
Labels: ✨ feature

#986 fix(button): fix config problem
  packages/web-vue/components/button/button-group.vue
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/button/context.ts
Labels: 🐞 bug

#933 feat(config-provider): add property isGlobal
  packages/web-vue/components/config-provider/README.en-US.md
  packages/web-vue/components/config-provider/README.zh-CN.md
  packages/web-vue/components/config-provider/config-provider.vue
  packages/web-vue/components/config-provider/index.ts
Labels: ✨ feature

#1015 feat(config): add updateAtScroll prop
  packages/web-vue/components/config-provider/README.en-US.md
  packages/web-vue/components/config-provider/README.zh-CN.md
  packages/web-vue/components/config-provider/TEMPLATE.md
  packages/web-vue/components/config-provider/config-provider.vue
  packages/web-vue/components/config-provider/context.ts
  packages/web-vue/components/config-provider/index.ts
  packages/web-vue/components/tooltip/README.en-US.md
  packages/web-vue/components/tooltip/README.zh-CN.md
  packages/web-vue/components/tooltip/tooltip.vue
  packages/web-vue/components/trigger/trigger.tsx
Labels: ✨ feature

#1017 feat(icon): add and modify icon
  packages/web-vue/icon/_svgs/edit/outline/attachment.svg
  packages/web-vue/icon/_svgs/edit/outline/link.svg
  packages/web-vue/icon/_svgs/general/outline/archive.svg
  packages/web-vue/icon/_svgs/general/outline/calendar-clock.svg
  packages/web-vue/icon/_svgs/general/outline/image-close.svg
  packages/web-vue/icon/_svgs/general/outline/lock.svg
  packages/web-vue/icon/_svgs/general/outline/palette.svg
  packages/web-vue/icon/_svgs/general/outline/unlock.svg
  packages/web-vue/icon/_svgs/interactive-button/outline/launch.svg
  packages/web-vue/icon/_svgs/interactive-button/outline/sync.svg
  packages/web-vue/icon/_svgs/logo/color/bytedance-color.svg
  packages/web-vue/icon/_svgs/logo/color/lark-color.svg
  packages/web-vue/icon/_svgs/logo/color/tiktok-color.svg
  packages/web-vue/icon/_svgs/logo/color/xigua-color.svg
Labels: ✨ feature

#1025 feat(tabs): add hideContent
  packages/web-vue/components/tabs/README.en-US.md
  packages/web-vue/components/tabs/README.zh-CN.md
  packages/web-vue/components/tabs/style/index.less
  packages/web-vue/components/tabs/tab-pane.vue
  packages/web-vue/components/tabs/tabs.tsx
Labels: ✨ feature

#1024 fix(tag): fix ts problem
  packages/web-vue/components/tag/interface.ts
Labels: typescript

#1023 feat(table): add v-model
  packages/web-vue/components/table/__demo__/editable.md
  packages/web-vue/components/table/__demo__/expand.md
  packages/web-vue/components/table/__demo__/row-selection.md
  packages/web-vue/components/table/__demo__/subtree.md
  packages/web-vue/components/table/context.ts
  packages/web-vue/components/table/hooks/use-expand.ts
  packages/web-vue/components/table/hooks/use-row-selection.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.ts
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: ✨ feature

#1022 fix(volar): fix volar failure problem
  packages/web-vue/components/components.d.ts
  packages/web-vue/components/index.ts
  packages/web-vue/copy-global.js
  packages/web-vue/package.json
Labels: 🐞 bug

#1018 perf(modal): esc to close last modal
  packages/web-vue/components/_hooks/use-popup-manager.ts
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/image/preview.vue
  packages/web-vue/components/message/message-list.tsx
  packages/web-vue/components/modal/__demo__/function.md
  packages/web-vue/components/modal/modal.vue
  packages/web-vue/components/notification/notification-list.tsx
  packages/web-vue/components/trigger/trigger.tsx
Labels: 💎 enhancement

#1026 fix(input-number): fix `error` problem
  packages/web-vue/components/input-number/input-number.tsx
Labels: 🐞 bug

#1020 feat(datepicker): add property exchangeTime
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/range-picker.vue
Labels: ✨ feature

#1021 feat(tree): add targetNode when operating a single node
  packages/web-vue/components/tree/tree.vue
Labels: 💎 enhancement

#1029 feat(notification): add button prop
  packages/web-vue/components/menu/style/index.less
  packages/web-vue/components/notification/interface.ts
  packages/web-vue/components/notification/notification-list.tsx
  packages/web-vue/components/notification/notification.vue
Labels: ✨ feature

#1034 fix(menu): the collected menu data is incomplete
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/menu/context.ts
  packages/web-vue/components/menu/hooks/use-menu-data-collector.ts
  packages/web-vue/components/menu/item.tsx
  packages/web-vue/components/menu/sub-menu.tsx
Labels: 🐞 bug

#1040 fix: checkbox disabled hover border color
  packages/web-vue/components/checkbox/style/index.less
Labels: 🔮 style

#1047 fix(table): fix outgoing parameter format error
  packages/web-vue/components/table/hooks/use-span.ts
  packages/web-vue/components/table/table-operation-td.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#1048 fix(input-number): fix clear btn style problem
  packages/web-vue/components/input-number/style/index.less
  packages/web-vue/components/input/style/index.less
  packages/web-vue/components/input/style/input.less
  packages/web-vue/components/input/style/size.less
Labels: 🔮 style

#1049 fix(popup): fix popupVisibleChange event problem
  packages/web-vue/components/_hooks/use-trigger.ts
Labels: 🐞 bug

#1050 fix(tabs): fix tabs title slot problem
  packages/web-vue/components/tabs/interface.ts
  packages/web-vue/components/tabs/tab-pane.vue
  packages/web-vue/components/tabs/tabs-nav.tsx
  packages/web-vue/components/tabs/tabs.tsx
Labels: 🐞 bug

#1052 fix(type): fix some type problem
  packages/web-vue/components/grid/grid-row.vue
  packages/web-vue/components/popconfirm/popconfirm.vue
  packages/web-vue/components/popover/popover.vue
  packages/web-vue/components/radio/radio.vue
  packages/web-vue/components/space/TEMPLATE.md
  packages/web-vue/components/space/space.tsx
Labels: 🐞 bug

#1053 fix(table): fix use desc problem with table
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table.tsx
Labels: 🔮 style

#1056 fix(cascader): fix search panel width problem
  packages/web-vue/components/cascader/style/index.less
Labels: 🔮 style

#1059 fix(carousel): fix trigger and autoPlay problem
  packages/web-vue/components/carousel/carousel-arrow.vue
  packages/web-vue/components/carousel/carousel-indicator.vue
  packages/web-vue/components/carousel/carousel.vue
  packages/web-vue/components/carousel/constants.ts
  packages/web-vue/components/carousel/interface.ts
Labels: 🐞 bug

#1060 fix(collapse): fix showExpandIcon invalid
  packages/web-vue/components/collapse/collapse-item.vue
Labels: 🐞 bug

#1061 fix: fix some type problem
  packages/web-vue/components/grid/grid-row.vue
  packages/web-vue/components/list/index.ts
Labels: 🐞 bug

#1030 fix(modal): add css style
  packages/web-vue/components/modal/style/index.less
Labels: 🔮 style

#1063 perf(trigger): update get first element method
  packages/web-vue/components/_components/resize-observer-v2.ts
  packages/web-vue/components/_components/resize-observer-v2.vue
  packages/web-vue/components/_hooks/use-children-components.ts
  packages/web-vue/components/_hooks/use-first-element.ts
  packages/web-vue/components/_utils/types.ts
  packages/web-vue/components/_utils/vue-utils.ts
  packages/web-vue/components/tabs/interface.ts
  packages/web-vue/components/tabs/tab-pane.vue
  packages/web-vue/components/tabs/tabs.tsx
  packages/web-vue/components/trigger/trigger.tsx
  packages/web-vue/components/trigger/utils.ts
Labels: 💎 enhancement
