Repository arco-design/arco-design-vue, pull requests merged in 2022-07, with the labels that each got.

#1350 docs: update pro faq
  packages/arco-vue-docs/docs/pro/faq.en-US.md
  packages/arco-vue-docs/docs/pro/faq.zh-CN.md
Labels: 📖 documentation

#1364 fix: fix typescript type declaration
  packages/arco-vue-docs/global.d.ts
  packages/web-vue-storybook/global.d.ts
  packages/web-vue/global.d.ts
Labels: 🐞 bug

#1366 fix(popconfirm): fix type color problem
  packages/web-vue/components/popconfirm/README.en-US.md
  packages/web-vue/components/popconfirm/README.zh-CN.md
  packages/web-vue/components/popconfirm/TEMPLATE.md
  packages/web-vue/components/popconfirm/__demo__/type.md
  packages/web-vue/components/popconfirm/style/index.less
  packages/web-vue/components/popconfirm/style/token.less
Labels: 🔮 style

#1368 fix(input-number): fix precision display problem
  packages/web-vue/components/input-number/input-number.tsx
Labels: 🐞 bug, 🔮 style

#1371 fix(select): fix firefox problem
  packages/web-vue/components/_components/input-label/style/input-label.less
Labels: 🐞 bug

#1370 fix: fix tree select model value bug
  packages/web-vue/components/tree-select/hooks/use-selected-state.ts
Labels: 🐞 bug

#1373 fix(table): fix tooltip update problem
  packages/web-vue/components/_components/auto-tooltip/auto-tooltip.tsx
Labels: 🐞 bug

#1372 docs: add faq docs
  packages/arco-vue-docs/docs/faq.en-US.md
  packages/arco-vue-docs/docs/faq.zh-CN.md
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/web-vue/components/empty/__demo__/custom.md
  packages/web-vue/components/table/__demo__/custom-dom.md
  packages/web-vue/components/upload/__demo__/request.md
Labels: 📖 documentation

#1342 feat(tag): tag support border and demo update
  packages/web-vue/components/tag/README.en-US.md
  packages/web-vue/components/tag/README.zh-CN.md
  packages/web-vue/components/tag/TEMPLATE.md
  packages/web-vue/components/tag/__demo__/bordered.md
  packages/web-vue/components/tag/__demo__/checkable.md
  packages/web-vue/components/tag/__demo__/dynamically.md
  packages/web-vue/components/tag/__demo__/icon.md
  packages/web-vue/components/tag/style/index.less
  packages/web-vue/components/tag/style/token.less
  packages/web-vue/components/tag/tag.vue
Labels: ✨ feature

#1379 fix(upload): Fix trailing space of upload-list-item.
  packages/web-vue/components/upload/upload-list-item.tsx
Labels: 🔮 style

#1397 fix(upload): fixed the problem when used with aliyun oss
  packages/web-vue/components/upload/utils.tsx
Labels: 🐞 bug

#1344 feat(collapse): support custom icon & update usage demo
  packages/web-vue/components/collapse/README.en-US.md
  packages/web-vue/components/collapse/README.zh-CN.md
  packages/web-vue/components/collapse/TEMPLATE.md
  packages/web-vue/components/collapse/__demo__/custom.md
  packages/web-vue/components/collapse/__demo__/expand-icon.md
  packages/web-vue/components/collapse/__demo__/extra.md
  packages/web-vue/components/collapse/__demo__/icon-position.md
  packages/web-vue/components/collapse/__demo__/nested.md
  packages/web-vue/components/collapse/collapse-item.tsx
  packages/web-vue/components/collapse/collapse.vue
  packages/web-vue/components/collapse/context.ts
  packages/web-vue/components/collapse/index.ts
Labels: ✨ feature

#1362 fix(tree): default-expand-selected does not work well with selected-keys
  packages/web-vue/components/tree/tree.vue
Labels: 🐞 bug

#1391 fix(modal): madal footer button not centered
  packages/web-vue/components/modal/style/index.less
Labels: 🔮 style

#1398 fix(tabs): fix focus style problem
  packages/web-vue/components/tabs/style/index.less
Labels: 🔮 style

#1399 feat: add header prop for Drawer component
  packages/web-vue/components/drawer/drawer.vue
  yarn.lock
Labels: ✨ feature

#1402 docs(arco-vue start): not support IE
  packages/arco-vue-docs/docs/start.en-US.md
  packages/arco-vue-docs/docs/start.zh-CN.md
Labels: 📖 documentation

#1437 fix(form): fix min-width problem
  packages/web-vue/components/form/style/index.less
Labels: 🐞 bug

#1438 fix(cascader): fix keyboard & scroll problem
  packages/web-vue/components/cascader/base-cascader-panel.tsx
  packages/web-vue/components/cascader/cascader.vue
  packages/web-vue/components/cascader/style/index.less
Labels: 🐞 bug

#1440 enhance(table): allow checked-row
  packages/web-vue/components/table/style/index.less
Labels: 💎 enhancement

#1442 fix(input-tag): fix the problem of can't delete when set max-tag-count
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: 🐞 bug

#1409 feat(drawer): add function call
  packages/web-vue/components/_utils/dom.ts
  packages/web-vue/components/components.ts
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/TEMPLATE.md
  packages/web-vue/components/drawer/__demo__/function.md
  packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/drawer/index.ts
  packages/web-vue/components/drawer/interface.ts
  packages/web-vue/components/index.ts
Labels: ✨ feature

#1410 feat(modal): support hide footer in function call
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/index.tsx
  packages/web-vue/components/modal/interface.ts
Labels: 💎 enhancement

#1445 feat(auto-complete): add footer slot
  packages/web-vue/components/auto-complete/README.en-US.md
  packages/web-vue/components/auto-complete/README.zh-CN.md
  packages/web-vue/components/auto-complete/TEMPLATE.md
  packages/web-vue/components/auto-complete/__demo__/footer.md
  packages/web-vue/components/auto-complete/auto-complete.tsx
Labels: ✨ feature

#1453 add function rowclass for table.tsx
  packages/web-vue/components/table/table.tsx
Labels: 💎 enhancement

#1466 feat(pagination): add autoAdjust prop
  packages/web-vue/components/pagination/pagination.tsx
Labels: ✨ feature

#1467 fix(timeline): fix update problem
  packages/web-vue/components/timeline/context.ts
  packages/web-vue/components/timeline/index.ts
  packages/web-vue/components/timeline/item.vue
  packages/web-vue/components/timeline/style/index.less
  packages/web-vue/components/timeline/timeline.tsx
Labels: 🐞 bug

#1447 feat(transfer): item slot add value param for issues #1295
  packages/web-vue/components/transfer/transfer-list-item.tsx
Labels: 💎 enhancement

#1408 feat: add input number readonly support
  packages/web-vue/components/input-number/input-number.tsx
  yarn.lock
Labels: 💎 enhancement

#1456 feat(tabs): add tabs trigger event(#1420)
  packages/web-vue/components/tabs/README.en-US.md
  packages/web-vue/components/tabs/README.zh-CN.md
  packages/web-vue/components/tabs/TEMPLATE.md
  packages/web-vue/components/tabs/__demo__/trigger.md
  packages/web-vue/components/tabs/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tabs/context.ts
  packages/web-vue/components/tabs/interface.ts
  packages/web-vue/components/tabs/tabs-tab.vue
  packages/web-vue/components/tabs/tabs.tsx
Labels: ✨ feature

#1470 enhance(table): support reactive columns
  packages/web-vue/components/table/table.tsx
Labels: 💎 enhancement

#1430 feat(dropdown-button): add new prop for icon slot: popup-visible
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/dropdown-button.vue
Labels: ✨ feature
