Repository arco-design/arco-design-vue, pull requests merged in 2022-06, with the labels that each got.

#1223 fix(space): fix key problem
  packages/web-vue/components/space/space.tsx
Labels: 🐞 bug

#1224 enhance(input-number): add keyboard event
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-number/style/index.less
Labels: 💎 enhancement

#1229 enhance(button): add focus style
  packages/web-vue/components/button/style/index.less
  packages/web-vue/components/button/style/token.less
  packages/web-vue/components/style/theme/css-variables.less
  packages/web-vue/components/style/theme/global.less
Labels: 💎 enhancement

#1230 enhance(cascader): add event
  packages/web-vue/components/cascader/cascader-panel.vue
  packages/web-vue/components/cascader/utils.ts
Labels: 💎 enhancement

#1231 enhance(trigger): not preventDefault when not Contextmenu
  packages/web-vue/components/trigger/trigger.tsx
Labels: 💎 enhancement

#1232 enhance(tree-select): clear input value when blur
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/tree-select/tree-select.vue
Labels: 💎 enhancement

#1233 enhance(virtual-list): minimum item height and total height are calcu…
  packages/web-vue/components/_components/virtual-list/hooks/use-item-height.ts
  packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx
  packages/web-vue/components/_components/virtual-list/hooks/use-scroll-to.ts
  packages/web-vue/components/_components/virtual-list/interface.ts
  packages/web-vue/components/_components/virtual-list/utils/algorithm.ts
  packages/web-vue/components/_components/virtual-list/utils/index.ts
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
Labels: 💎 enhancement

#1217 feat(textarea): Correction of text description of auto-size
  packages/web-vue/components/textarea/__demo__/auto-size.md
Labels: 📖 documentation

#1227 fix(mention): fix style problem
  packages/web-vue/components/mention/style/index.ts
Labels: 🐞 bug

#1248 feat(table): add sticky header
  packages/web-vue/components/_components/virtual-list/filler.vue
  packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
  packages/web-vue/components/table/TEMPLATE.md
  packages/web-vue/components/table/__demo__/fixed-group.md
  packages/web-vue/components/table/__demo__/resize.md
  packages/web-vue/components/table/__demo__/sticky.md
  packages/web-vue/components/table/__demo__/summary.md
  packages/web-vue/components/table/__demo__/virtual-list.md
  packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/table/hooks/use-drag.ts
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/style/index.less
  packages/web-vue/components/table/table-column.tsx
  packages/web-vue/components/table/table-td.tsx
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table-tr.tsx
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
  packages/web-vue/components/tree/__test__/__snapshots__/demo.test.ts.snap
Labels: 🐞 bug, ✨ feature

#1262 fix(modal): reset overflow when unmount
  packages/web-vue/components/modal/modal.vue
Labels: 🐞 bug

#1263 fix(input): fix form validate problem
  packages/web-vue/components/input-tag/input-tag.tsx
  packages/web-vue/components/input/input.tsx
  packages/web-vue/components/input/style/index.less
Labels: 🐞 bug

#1264 enhance(tabs): add focus style and keyboard event
  packages/web-vue/components/tabs/style/index.less
  packages/web-vue/components/tabs/tabs-tab.vue
Labels: 💎 enhancement

#1271 fix(select): fix fieldNames problem
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/style/animation/zoom.less
Labels: 🐞 bug

#1273 fix(space): use flex item
  packages/web-vue/components/space/style/index.less
Labels: 🔮 style

#1274 fix(select): fix empty value style problem
  packages/web-vue/components/_components/input-label/style/input-label.less
Labels: 🔮 style

#1098 feat(scrollbar): add scrollbar component
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/web-vue/components/_hooks/use-component-ref.ts
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/index.less
  packages/web-vue/components/index.ts
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/scrollbar/README.en-US.md
  packages/web-vue/components/scrollbar/README.zh-CN.md
  packages/web-vue/components/scrollbar/TEMPLATE.md
  packages/web-vue/components/scrollbar/__demo__/basic.md
  packages/web-vue/components/scrollbar/__demo__/type.md
  packages/web-vue/components/scrollbar/index.ts
  packages/web-vue/components/scrollbar/interface.ts
  packages/web-vue/components/scrollbar/scrollbar.vue
  packages/web-vue/components/scrollbar/style/index.less
  packages/web-vue/components/scrollbar/style/index.ts
  packages/web-vue/components/scrollbar/style/token.less
  packages/web-vue/components/scrollbar/thumb.vue
  packages/web-vue/components/select/select-dropdown.vue
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#1277 fix(space): fix vertical problem
  packages/web-vue/components/space/style/index.less
  packages/web-vue/components/table/README.en-US.md
  packages/web-vue/components/table/README.zh-CN.md
Labels: 🔮 style

#1278 fix(table): fix align problem
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
Labels: 🐞 bug

#1303 feat(modal): add class and style
  packages/web-vue/components/modal/modal.vue
Labels: ✨ feature

#1297 fix(menu): the horizontal menu cannot be expanded after being collapsed
  packages/web-vue-storybook/stories/components/custom-sub-menu.vue
  packages/web-vue-storybook/stories/components/menu.vue
  packages/web-vue/components/menu/overflow-wrap.tsx
Labels: 🐞 bug

#1301 fix(virtual-list): scrollIntoView has an wrong result
  packages/web-vue-storybook/stories/components/json.ts
  packages/web-vue-storybook/stories/components/virtual-list.vue
  packages/web-vue/components/_components/virtual-list/hooks/use-range-state.ts
  packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx
  packages/web-vue/components/_components/virtual-list/utils/index.ts
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
Labels: 🐞 bug

#1304 feat(table): add methods
  packages/web-vue/components/table/hooks/use-expand.ts
  packages/web-vue/components/table/hooks/use-filter.ts
  packages/web-vue/components/table/hooks/use-row-selection.ts
  packages/web-vue/components/table/hooks/use-sorter.ts
  packages/web-vue/components/table/table-th.tsx
  packages/web-vue/components/table/table.tsx
Labels: ✨ feature

#1305 feat(form): support param
  packages/web-vue/components/form/form.vue
Labels: ✨ feature

#1317 fix(tag): fix display style
  packages/web-vue/components/tag/style/index.less
Labels: 🔮 style

#1320 docs(statistic): countdown usage demo
  packages/web-vue/components/statistic/README.en-US.md
  packages/web-vue/components/statistic/README.zh-CN.md
  packages/web-vue/components/statistic/__demo__/countdown.md
  packages/web-vue/components/statistic/__demo__/prefix.md
  packages/web-vue/components/statistic/countdown.vue
  packages/web-vue/components/statistic/statistic.vue
Labels: ✨ feature

#1329 fix(input-number): fix clear error outside of form
  packages/web-vue/components/input-number/input-number.tsx
Labels: 🐞 bug

#1331 fix(tree): check on the node in the half-selected state have a wrong result
  packages/web-vue/components/tree/utils/check-utils.ts
Labels: 🐞 bug

#1337 fix(trigger): fix animation problem
  packages/web-vue/components/trigger/trigger.tsx
Labels: 💎 enhancement

#1335 fix(input): fix event problem
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-tag/input-tag.tsx
Labels: 🐞 bug

#1336 fix(modal): fix draggable problem
  packages/web-vue/components/modal/hooks/use-draggable.ts
Labels: 🐞 bug

#1339 docs: update docs
  packages/arco-vue-docs/docs/start.en-US.md
  packages/arco-vue-docs/docs/start.zh-CN.md
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/select.tsx
Labels: 📖 documentation

#1340 fix(virtual-list): fix list error when data changed
  packages/web-vue-storybook/stories/components/virtual-list.vue
  packages/web-vue/components/_components/virtual-list/hooks/use-item-height.ts
  packages/web-vue/components/_components/virtual-list/hooks/use-range-state.ts
  packages/web-vue/components/_components/virtual-list/hooks/use-scroll-to.ts
  packages/web-vue/components/_components/virtual-list/utils/index.ts
  packages/web-vue/components/_components/virtual-list/virtual-list.vue
Labels: 🐞 bug
