Repository arco-design/arco-design-vue, pull requests merged in 2023-06, with the labels that each got.

#2448 feat(config-provider): empty slots add component attribute
  packages/web-vue/components/cascader/base-cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-search-panel.tsx
  packages/web-vue/components/config-provider/__demo__/empty.md
  packages/web-vue/components/config-provider/config-provider.vue
  packages/web-vue/components/empty/empty.tsx
  packages/web-vue/components/list/list.tsx
  packages/web-vue/components/select/select-dropdown.vue
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: feature request

#2465 fix(modal): fix modal confirm missing warning icon in the title
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/__demo__/confirm.md
  packages/web-vue/components/modal/index.tsx
Labels: type: 🔮 style, type: chore

#2464 feat(alert): add center prop
  packages/web-vue/components/alert/README.en-US.md
  packages/web-vue/components/alert/README.zh-CN.md
  packages/web-vue/components/alert/alert.vue
  packages/web-vue/components/alert/style/index.less
Labels: type: feature request

#2461 feat(number-input): ignoring mode when hide button
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/input-number.tsx
Labels: type: enhancement, type: chore

#2474 feat(empty): add new prop
  packages/web-vue/components/config-provider/TEMPLATE.md
  packages/web-vue/components/empty/empty.tsx
Labels: type: feature request

#2437 fix(date-picker): add getDefaultValueFormat to solve v-model for week…
  packages/web-vue/components/date-picker/hooks/use-format.ts
Labels: type: 🐞 bug

#2429 feat(select): the header and footer are displayed in the empty state …
  packages/web-vue/components/select/__demo__/footer.md
  packages/web-vue/components/select/__demo__/header.md
  packages/web-vue/components/select/interface.ts
  packages/web-vue/components/select/select-dropdown.vue
  packages/web-vue/components/select/select.tsx
Labels: type: feature request

#2417 feat(tree-select): Add header and footer slots to tree-select
  packages/web-vue/components/tree-select/README.en-US.md
  packages/web-vue/components/tree-select/README.zh-CN.md
  packages/web-vue/components/tree-select/TEMPLATE.md
  packages/web-vue/components/tree-select/__demo__/dropdown-slots.md
  packages/web-vue/components/tree-select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/tree-select/hooks/use-filter-tree-node.ts
  packages/web-vue/components/tree-select/style/index.less
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: feature request

#2356 feat(mention): search event add a prefix param
  packages/web-vue/components/mention/README.en-US.md
  packages/web-vue/components/mention/README.zh-CN.md
  packages/web-vue/components/mention/mention.tsx
Labels: type: feature request

#2303 feat(spin): add hideIcon prop and tip slot.
  packages/web-vue/components/spin/README.en-US.md
  packages/web-vue/components/spin/README.zh-CN.md
  packages/web-vue/components/spin/spin.tsx
Labels: type: feature request

#2476 自定义prefix-cls时，badge样式异常问题
  packages/web-vue/components/badge/style/index.less
Labels: type: 🐞 bug

#2487 fix(select): fix search pointer problem
  packages/web-vue/components/_components/input-label/style/input-label.less
Labels: type: 🐞 bug

#2488 fix(select-tree): fix search problem
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/tree.vue
Labels: type: 🐞 bug

#2529 feat(config-provider): add exchangeTime
  packages/web-vue/components/config-provider/config-provider.vue
  packages/web-vue/components/config-provider/context.ts
  packages/web-vue/components/date-picker/range-picker.vue
Labels: type: feature request
