Repository arco-design/arco-design-vue, pull requests merged in 2023-03, with the labels that each got.

#2217 feat: add calendar
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/web-vue/components/_utils/date.ts
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/calendar/README.en-US.md
  packages/web-vue/components/calendar/README.zh-CN.md
  packages/web-vue/components/calendar/TEMPLATE.md
  packages/web-vue/components/calendar/__demo__/basic.md
  packages/web-vue/components/calendar/__test__/demo.test.ts
  packages/web-vue/components/calendar/calendar.tsx
  packages/web-vue/components/calendar/header.tsx
  packages/web-vue/components/calendar/hooks/useCellClassName.ts
  packages/web-vue/components/calendar/index.ts
  packages/web-vue/components/calendar/month.tsx
  packages/web-vue/components/calendar/style/index.less
  packages/web-vue/components/calendar/style/index.ts
  packages/web-vue/components/calendar/style/token.less
  packages/web-vue/components/calendar/week.tsx
  packages/web-vue/components/calendar/year.tsx
  packages/web-vue/components/components.ts
  packages/web-vue/components/index.less
  packages/web-vue/components/index.ts
  packages/web-vue/components/locale/interface.ts
  packages/web-vue/components/locale/lang/ar-eg.ts
  packages/web-vue/components/locale/lang/de-de.ts
  packages/web-vue/components/locale/lang/en-us.ts
  packages/web-vue/components/locale/lang/es-es.ts
  packages/web-vue/components/locale/lang/fr-fr.ts
  packages/web-vue/components/locale/lang/id-id.ts
  packages/web-vue/components/locale/lang/it-it.ts
  packages/web-vue/components/locale/lang/ja-jp.ts
  packages/web-vue/components/locale/lang/ko-kr.ts
  packages/web-vue/components/locale/lang/ms-my.ts
  packages/web-vue/components/locale/lang/pt-pt.ts
  packages/web-vue/components/locale/lang/th-th.ts
  packages/web-vue/components/locale/lang/zh-cn.ts
  packages/web-vue/components/locale/lang/zh-tw.ts
Labels: type: feature request

#2199 fix(list): list supports backend data pagination
  packages/web-vue/components/list/list.tsx
Labels: type: 🐞 bug

#2188 fix(input): adjust maxLength checking mechanism
  packages/web-vue/components/input/input.tsx
Labels: type: 🐞 bug

#2240 enhance(form): add i18n validate message
  packages/web-vue/components/form/form-item.vue
  packages/web-vue/components/locale/index.ts
  packages/web-vue/components/locale/interface.ts
  packages/web-vue/components/locale/lang/en-us.ts
  packages/web-vue/components/locale/lang/ja-jp.ts
  packages/web-vue/components/locale/lang/zh-cn.ts
  packages/web-vue/components/locale/lang/zh-tw.ts
  packages/web-vue/package.json
  yarn.lock
Labels: type: enhancement

#2222 feat(i18n): locale support vi-vN
  packages/arco-vue-docs/docs/i18n.en-US.md
  packages/arco-vue-docs/docs/i18n.zh-CN.md
  packages/web-vue/components/config-provider/__demo__/basic.md
  packages/web-vue/components/locale/lang/vi-VN.ts
Labels: type: enhancement

#2242 fix(form): fix field array problem
  packages/web-vue/components/_utils/get-value-by-path.ts
  packages/web-vue/components/form/__demo__/dynamic.md
Labels: type: 🐞 bug

#2241 fix(slider): fix default value problem
  packages/web-vue/components/slider/__demo__/range.md
  packages/web-vue/components/slider/slider.vue
Labels: type: 🐞 bug

#2239 fix(calendar): fix some style problems
  packages/web-vue/components/calendar/style/index.less
Labels: type: 🔮 style

#2228 fix(tree): change the order of select and check emit
  packages/web-vue/components/tree/tree.vue
Labels: type: 🐞 bug

#2219 feat(locale): add Vietnamese and Khmer (Cambodian) language support
  packages/arco-vue-docs/docs/i18n.en-US.md
  packages/arco-vue-docs/docs/i18n.zh-CN.md
  packages/web-vue/components/locale/lang/km-kh.ts
  packages/web-vue/components/locale/lang/vi-vn.ts
Labels: type: enhancement

#2168 enhance(virtual-list-v2): optimize type
  packages/web-vue/components/_components/virtual-list-v2/interface.ts
Labels: type: typescript

#2204 enhance(upload): beforeUpload allows to return a boolean value
  packages/web-vue/components/upload/upload.tsx
Labels: type: typescript

#2257 fix(select): 不允许自动创建空字符串条目。含有空字符串的下拉选项，清空时将值设置为undefined
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/select/utils.ts
Labels: type: 🐞 bug

#2270 fix(datepicker): fix year range problem
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/package.json
Labels: type: 🐞 bug

#2265 fix(select): fix select slot options
  packages/web-vue/components/select/hooks/use-options.ts
Labels: type: 🐞 bug

#2273 fix(trigger): Support position calculation within Shadow DOM.
  packages/web-vue/components/trigger/utils.ts
Labels: type: enhancement

#2285 fix(select): sync _value and modelValue
  packages/web-vue/components/select/select.tsx
Labels: type: 🐞 bug

#2272 fix(upload): fix slot parameter problem
  packages/web-vue/components/upload/upload-list-item.tsx
Labels: type: 🐞 bug

#2295 fix(list): fix reach problem
  packages/web-vue/components/list/list.tsx
Labels: type: 🐞 bug

#2278 fix(Transfer): 修复 title 中内容 ellipsis 失效
  packages/web-vue/components/transfer/style/index.less
  packages/web-vue/components/transfer/transfer-view.vue
Labels: type: 🐞 bug
