Repository arco-design/arco-design-vue, pull requests merged in 2023-04, with the labels that each got.

#2300 fix(trigger): add try-catch
  packages/web-vue/components/trigger/utils.ts
Labels: type: 🐞 bug

#2314 feat(Transfer): add custom-header for transfer
  packages/web-vue/components/transfer/README.en-US.md
  packages/web-vue/components/transfer/README.zh-CN.md
  packages/web-vue/components/transfer/TEMPLATE.md
  packages/web-vue/components/transfer/__demo__/custom-header.md
  packages/web-vue/components/transfer/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/transfer/transfer.vue
Labels: type: feature request

#2302 fix: 修复exchange-time在select下没生效的问题
  packages/web-vue/components/date-picker/range-picker.vue
Labels: type: 🐞 bug

#2223 feat(switch): 开关新增checkedText、uncheckedText
  packages/web-vue/components/switch/switch.vue
Labels: type: feature request

#2264 feat(date-picker): add property abbreviation
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/interface.ts
  packages/web-vue/components/date-picker/panels/month/index.vue
  packages/web-vue/components/date-picker/picker-panel.vue
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker-panel.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: type: feature request

#2192 feat(tree): add data-level and data-key attributes to tree nodes
  packages/web-vue/components/tree/base-node.vue
Labels: type: feature request

#2325 fix: fixed individual cases where tab slots are not updated
  packages/web-vue/components/tabs/tab-pane.vue
Labels: type: 🐞 bug

#2327 fix: 修复写法问题导致sizeStyle没有传递的问题
  packages/web-vue/components/image/image.vue
Labels: type: 🐞 bug

#2326 fix(cascader): 修复搜索结果展示异常(#2324)
  packages/web-vue/components/cascader/style/index.less
Labels: type: 🐞 bug

#2337 fix(table): fix virtual style problem
  packages/web-vue/components/table/style/index.less
Labels: type: 🔮 style

#2347 docs(modal): modal文档中ModalConfig的默认值
  packages/web-vue/components/modal/interface.ts
Labels: type: docs

#2349 fix(date-picker): fix class names
  packages/web-vue/components/date-picker/style/index.less
Labels: type: 🐞 bug

#2378 fix(select): fix enter problem
  packages/web-vue/components/select/hooks/use-select.ts
Labels: type: 🐞 bug

#2373 fix(CheckBox): value 设置为boolean类型后控制台报警告 #2372
  packages/web-vue/components/checkbox/checkbox.tsx
Labels: type: typescript

#2358 feat(drawer/modal): add onOk/onCancel event params
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/modal.vue
Labels: type: enhancement
