Repository arco-design/arco-design-vue, pull requests merged in 2023-01, with the labels that each got.

#2031 fix(tabs): fix capsule scroll problem
  packages/web-vue/components/tabs/__demo__/editable.md
  packages/web-vue/components/tabs/style/index.less
  packages/web-vue/components/tabs/tabs-nav.tsx
  packages/web-vue/components/tabs/utils.ts
Labels: type: 🐞 bug

#2030 enhance(icon): enhance click event
  packages/arco-vue-scripts/src/scripts/icongen/svgo.config.ts
  packages/arco-vue-scripts/src/scripts/icongen/vue-template.ts
Labels: type: enhancement

#2029 fix(checkbox): fix value typescript
  packages/web-vue/components/checkbox/checkbox.tsx
Labels: type: typescript

#2028 fix(table): fix width problem when scale
  packages/web-vue/components/table/style/index.less
Labels: type: 🐞 bug

#2027 fix: fix typescript problem
  packages/web-vue/components/components.ts
Labels: type: 🐞 bug

#2048 fix(upload): fix upload status
  packages/web-vue/components/upload/upload.tsx
Labels: type: 🐞 bug

#2044 fix(switch): custom color style erro when type is line
  packages/web-vue/components/switch/style/index.less
  packages/web-vue/components/switch/switch.vue
Labels: type: 🐞 bug

#2037 feat(slider): add show-tooltip props
  packages/web-vue/components/slider/README.en-US.md
  packages/web-vue/components/slider/README.zh-CN.md
  packages/web-vue/components/slider/slider-button.vue
  packages/web-vue/components/slider/slider.vue
Labels: type: feature request

#2035 docs: 修改vite最新官网地址
  packages/arco-vue-docs/docs/pro/build.en-US.md
  packages/arco-vue-docs/docs/pro/build.zh-CN.md
  packages/arco-vue-docs/docs/pro/npm-scripts.en-US.md
  packages/arco-vue-docs/docs/pro/npm-scripts.zh-CN.md
Labels: type: docs

#2022 feat(mention): add focus and blur methods
  packages/web-vue/components/mention/README.en-US.md
  packages/web-vue/components/mention/README.zh-CN.md
  packages/web-vue/components/mention/mention.tsx
Labels: type: feature request

#1958 feat(date-picker): add blur trigger validate
  packages/web-vue/components/_components/picker/input.vue
  packages/web-vue/components/date-picker/picker.vue
Labels: type: feature request

#2049 feat(upload): add new prop
  packages/web-vue/components/upload/context.ts
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: type: feature request
