Repository arco-design/arco-design-vue, pull requests merged in 2023-08, with the labels that each got.

#2604 fix(grid): fix the problem of using v-show in a-grid-item, the initia…
  packages/web-vue/components/grid/grid-item.vue
Labels: type: 🐞 bug

#2628 fix(modal): fix interface problem
  packages/web-vue/components/modal/interface.ts
Labels: type: typescript

#2605 💎 Enhancement: support whether to hide the title
  packages/web-vue/components/modal/CHANGELOG.md
  packages/web-vue/components/modal/CHANGELOG.zh-CN.md
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/interface.ts
  packages/web-vue/components/modal/modal.vue
Labels: type: feature request

#2596 feat(auto-complete): add virtual list support
  packages/web-vue/components/auto-complete/README.en-US.md
  packages/web-vue/components/auto-complete/README.zh-CN.md
  packages/web-vue/components/auto-complete/__demo__/virtual-list.md
  packages/web-vue/components/auto-complete/auto-complete.tsx
Labels: type: feature request

#2591 feat(timeline): add label slot
  packages/web-vue/components/timeline/README.en-US.md
  packages/web-vue/components/timeline/README.zh-CN.md
  packages/web-vue/components/timeline/TEMPLATE.md
  packages/web-vue/components/timeline/__demo__/custom.md
  packages/web-vue/components/timeline/item.vue
Labels: type: feature request

#2626 style: fix IDE-reported ESLint Error: Remove ␍ Error
  .gitattributes
  .prettierrc.js
  packages/arco-changelog/.prettierrc.js
  packages/arco-vue-docs/.prettierrc.js
  packages/arco-vue-scripts/.prettierrc.js
  packages/vite-plugin-arco-vue-docs/.prettierrc.js
  packages/web-vue-storybook/.prettierrc.js
  packages/web-vue/.prettierrc.js
Labels: type: 🐞 bug, type: perf

#2625 feat: added image-preview-action type definition
  packages/web-vue/components/components.ts
Labels: type: typescript

#2616 feat: enhance image preview
  packages/web-vue/components/image/README.en-US.md
  packages/web-vue/components/image/README.zh-CN.md
  packages/web-vue/components/image/TEMPLATE.md
  packages/web-vue/components/image/image.vue
  packages/web-vue/components/image/interface.ts
  packages/web-vue/components/image/preview-toolbar.vue
  packages/web-vue/components/image/preview.vue
  packages/web-vue/components/image/utils/get-scale.ts
Labels: type: feature request

#2633 fix: fix install problem
  packages/web-vue/components/arco-vue.ts
Labels: type: 🐞 bug

#2656 feat(transfer): add input-search props
  packages/web-vue/components/grid/__demo__/grid.md
  packages/web-vue/components/transfer/README.en-US.md
  packages/web-vue/components/transfer/README.zh-CN.md
  packages/web-vue/components/transfer/__demo__/search.md
  packages/web-vue/components/transfer/transfer-view.vue
  packages/web-vue/components/transfer/transfer.vue
  packages/web-vue/components/trigger/README.en-US.md
  packages/web-vue/components/trigger/README.zh-CN.md
  packages/web-vue/components/trigger/TEMPLATE.md
Labels: type: feature request

#2634 chore(gitattributes): fix lf convert to crlf
  .gitattributes
Labels: type: chore

#2668 enhance(input-number): enhance step button
  packages/web-vue/components/input-number/input-number.tsx
Labels: type: enhancement

#2665 fix(virtual-list): fix the wrong scrolling position of the virtual list
  packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue
Labels: type: 🐞 bug
