Repository arco-design/arco-design-vue, pull requests merged in 2023-07, with the labels that each got.

#2540 fix(table): fix the bug of merging cells in subtrees
  packages/web-vue/components/table/hooks/use-span.ts
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#2561 fix: adaptive height issue with divider
  packages/web-vue/components/divider/style/index.less
Labels: type: enhancement

#1935 fix(image): icon not centered without alt or description in error state
  packages/web-vue/components/image/image.vue
Labels: type: 🐞 bug

#2563 fix: icon not centered without alt or description in error state
  packages/web-vue/components/image/image.vue
Labels: type: 🐞 bug

#2573 feat(tree-select): header and footer visibility in empty data state
  packages/web-vue/components/tree-select/__demo__/dropdown-slots.md
  packages/web-vue/components/tree-select/interface.ts
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: feature request

#2570 fix(Table): pass .raw to rowClass, 跟文档和 renderSummaryRow 一样保持一致 (#2553)
  packages/web-vue/components/table/table.tsx
Labels: type: 🐞 bug

#2566 docs: fix errors in the pinia example in Arco Pro
  packages/arco-vue-docs/docs/pro/state-management-pinia.en-US.md
  packages/arco-vue-docs/docs/pro/state-management-pinia.zh-CN.md
  yarn.lock
Labels: type: docs

#2577 feat(cascader): add virtual list support
  packages/web-vue/components/cascader/README.en-US.md
  packages/web-vue/components/cascader/README.zh-CN.md
  packages/web-vue/components/cascader/TEMPLATE.md
  packages/web-vue/components/cascader/__demo__/virtual.md
  packages/web-vue/components/cascader/base-cascader-panel.tsx
  packages/web-vue/components/cascader/cascader-column.tsx
  packages/web-vue/components/cascader/cascader.vue
Labels: type: feature request

#2568 fix(tree-select): replace border with bordered
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: 🐞 bug

#2560 feat: add slots for input-number box value manipulation icons
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/TEMPLATE.md
  packages/web-vue/components/input-number/__demo__/step-icon.md
  packages/web-vue/components/input-number/input-number.tsx
Labels: type: feature request

#2578 fix(result): fix 500 image problem
  packages/web-vue/components/result/500.tsx
Labels: type: 🐞 bug

#2544 feat(list): Scroll maxHeight supports string type
  packages/web-vue/components/list/README.en-US.md
  packages/web-vue/components/list/README.zh-CN.md
  packages/web-vue/components/list/list.tsx
Labels: type: feature request

#2580 fix(tree-select): fix border problem
  packages/web-vue/components/tree-select/tree-select.vue
Labels: type: 🐞 bug

#2583 fix(typography): enhanced typography styles for handling long words
  packages/web-vue/components/typography/style/index.less
Labels: type: 🔮 style

#2600 fix(statistic): fix value style problem
  packages/arco-vue-docs/docs/start.en-US.md
  packages/arco-vue-docs/docs/start.zh-CN.md
  packages/web-vue/components/statistic/style/index.less
  packages/web-vue/components/statistic/style/token.less
  packages/web-vue/components/table/TEMPLATE.md
Labels: type: 🐞 bug

#2598 fix(table): fix fixed resize problem
  packages/web-vue/components/table/interface.ts
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: type: 🐞 bug

#2503 fix(table): draggable tree table
  packages/web-vue/components/table/hooks/use-drag.ts
  packages/web-vue/components/table/table.tsx
  packages/web-vue/components/table/utils.ts
Labels: type: 🐞 bug
