Repository arco-design/arco-design-vue, pull requests merged in 2023-12, with the labels that each got.

#2865 fix(range-picker): resolve arrow click issue in range-picker
  packages/web-vue/components/date-picker/hooks/use-range-header-value.ts
Labels: type: 🐞 bug

#2823 feat(verification-code): add verification-code component
  packages/arco-vue-docs/components/aside-nav/style.less
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/components.ts
  packages/web-vue/components/index.less
  packages/web-vue/components/index.ts
  packages/web-vue/components/verification-code/README.en-US.md
  packages/web-vue/components/verification-code/README.zh-CN.md
  packages/web-vue/components/verification-code/TEMPLATE.md
  packages/web-vue/components/verification-code/__demo__/basic.md
  packages/web-vue/components/verification-code/__demo__/form.md
  packages/web-vue/components/verification-code/__demo__/formatter.md
  packages/web-vue/components/verification-code/__demo__/masked.md
  packages/web-vue/components/verification-code/__demo__/separator.md
  packages/web-vue/components/verification-code/__demo__/status.md
  packages/web-vue/components/verification-code/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/verification-code/__test__/demo.test.ts
  packages/web-vue/components/verification-code/index.ts
  packages/web-vue/components/verification-code/style/index.less
  packages/web-vue/components/verification-code/style/index.ts
  packages/web-vue/components/verification-code/style/token.less
  packages/web-vue/components/verification-code/verification-code.tsx
Labels: type: feature request

#2828 fix(Pagination): Fix the issue with page being 0
  packages/web-vue/components/pagination/pagination.tsx
Labels: type: 🐞 bug

#2825 enhance(button): TS type optimization
  packages/web-vue/components/button/button-group.vue
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/button/interface.ts
Labels: type: typescript

#2867 enhance(cascader): add props watch
  packages/arco-vue-docs/components/aside-nav/style.less
  packages/web-vue/components/cascader/cascader.vue
Labels: type: enhancement

#2784 feat(input-password): Enhance the input-password props
  packages/web-vue/components/input/README.en-US.md
  packages/web-vue/components/input/README.zh-CN.md
  packages/web-vue/components/input/__demo__/password.md
  packages/web-vue/components/input/input-password.vue
Labels: type: feature request

#2790 feat(watermark): fontColor follows the theme
  packages/web-vue/components/watermark/hooks/use-theme.ts
  packages/web-vue/components/watermark/watermark.tsx
Labels: type: feature request

#2881 fix(select): fix default problem
  packages/web-vue/components/select/select.tsx
Labels: type: 🐞 bug
