Repository arco-design/arco-design-vue, pull requests merged in 2023-02, with the labels that each got.

#2062 docs(Tooltip): Correction of text description
  packages/web-vue/components/tooltip/__demo__/color.md
Labels: type: docs

#2077 fix(scrollbar): fix ts declaration error
  packages/web-vue/components/scrollbar/scrollbar.vue
Labels: type: typescript

#1777 fix(input-number): fix step-button is not properly disabled or enabled when min or max is changed
  packages/web-vue/components/input-number/input-number.tsx
Labels: type: 🐞 bug

#1952 fix(input-number): Invalid input values can always be corrected(#1706)
  packages/web-vue/components/slider/slider.vue
Labels: type: enhancement

#2087 feat: 修复文档描述错误
  packages/web-vue/components/upload/upload.tsx
Labels: type: docs

#2099 select add header slot
  packages/web-vue/components/select/README.en-US.md
  packages/web-vue/components/select/README.zh-CN.md
  packages/web-vue/components/select/TEMPLATE.md
  packages/web-vue/components/select/__demo__/header.md
  packages/web-vue/components/select/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/select/select-dropdown.vue
  packages/web-vue/components/select/select.tsx
  packages/web-vue/components/select/style/index.less
Labels: type: feature request

#2091 fix(menu): fix the hotreload problem
  packages/web-vue/components/menu/sub-menu.tsx
Labels: type: 🐞 bug

#2072 feat(date-picker): add disable input support
  packages/web-vue-storybook/stories/components/date-picker.vue
  packages/web-vue/components/date-picker/README.en-US.md
  packages/web-vue/components/date-picker/README.zh-CN.md
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
Labels: type: feature request

#2105 fix(tabs): fix nav-ink problem
  packages/web-vue/components/tabs/tabs-nav.tsx
Labels: type: 🐞 bug

#2060 Feat upload extra button
  packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/upload/style/index.less
  packages/web-vue/components/upload/upload-list-item.tsx
  packages/web-vue/components/upload/upload-picture-item.tsx
  packages/web-vue/components/upload/upload.tsx
Labels: type: feature request

#2064 feat(drawer): add `before-open` and `before-close` events
  packages/web-vue/components/drawer/drawer.vue
  packages/web-vue/components/drawer/interface.ts
Labels: type: feature request

#2078 feat(dropdown): add hide-on-select props
  packages/web-vue/components/dropdown/README.en-US.md
  packages/web-vue/components/dropdown/README.zh-CN.md
  packages/web-vue/components/dropdown/dropdown-button.vue
  packages/web-vue/components/dropdown/dropdown.vue
Labels: type: feature request

#2106 fix(notification): fix update problem
  packages/web-vue/components/notification/__demo__/update_duration.md
  packages/web-vue/components/notification/__demo__/update_notification.md
  packages/web-vue/components/notification/notification-list.tsx
Labels: type: 🐞 bug

#2090 enhance: update the triggerProps types of some components
  packages/web-vue/components/auto-complete/auto-complete.tsx
  packages/web-vue/components/date-picker/picker.vue
  packages/web-vue/components/date-picker/range-picker.vue
  packages/web-vue/components/menu/base-menu.vue
  packages/web-vue/components/time-picker/time-picker.vue
Labels: type: typescript

#2107 feat(select): add defaultActiveFirstOption prop
  packages/web-vue/components/select/hooks/use-select.ts
  packages/web-vue/components/select/select.tsx
Labels: type: feature request

#2110 fix(DatePicker): 修复因dayjs不支持季度解析导致返回错误的date #2057
  packages/web-vue/components/_utils/date.ts
  packages/web-vue/components/_utils/is.ts
Labels: type: 🐞 bug

#2158 fix(form): in formItem, isError uses props.validateStatus first
  packages/web-vue/components/form/form-item.vue
Labels: type: 🐞 bug

#2155 enhance(modal): add update method of function call
  packages/web-vue/components/drawer/README.en-US.md
  packages/web-vue/components/drawer/README.zh-CN.md
  packages/web-vue/components/drawer/index.ts
  packages/web-vue/components/drawer/interface.ts
  packages/web-vue/components/modal/README.en-US.md
  packages/web-vue/components/modal/README.zh-CN.md
  packages/web-vue/components/modal/index.tsx
  packages/web-vue/components/modal/interface.ts
Labels: type: enhancement

#2124 fix(checkbox): remove the hover style in the checkbox focus state
  packages/web-vue/components/checkbox/style/index.less
Labels: type: 🔮 style

#2169 fix(input-number): fix step display
  packages/web-vue/components/input-number/README.en-US.md
  packages/web-vue/components/input-number/README.zh-CN.md
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-number/style/index.less
Labels: type: 🐞 bug
