Repository arco-design/arco-design-vue, pull requests merged in 2023-05, with the labels that each got.

#2389 feat(image-preview-group): add actions slot
  packages/web-vue/components/image/preview-group.vue
Labels: type: feature request

#2363 feat(cascader): support full path search
  packages/web-vue/components/cascader/cascader.vue
Labels: type: enhancement

#2412 enhance: single input add title
  packages/web-vue/components/_components/input-label/input-label.tsx
Labels: type: enhancement

#2390 fix: 修复divider的margin无法设置为0的问题
  packages/web-vue/components/divider/divider.tsx
Labels: type: 🐞 bug

#2359 fix(date-picker): fix missing props declear
  packages/web-vue/components/date-picker/pickers/date-picker.tsx
Labels: type: typescript

#2426 fix(drawer & modal ): fix onOk & onCancel type error in function call
  packages/web-vue/components/drawer/interface.ts
  packages/web-vue/components/modal/interface.ts
Labels: type: typescript

#2441 fix(modal): add width attribute, fullscreen width become invalid.
  packages/web-vue/components/modal/modal.vue
Labels: type: 🐞 bug

#2467 fix(modal): can not set width attribute
  packages/web-vue/components/modal/modal.vue
Labels: type: 🐞 bug
