Repository arco-design/arco-design-vue, pull requests merged in 2023-10, with the labels that each got.

#2737 enhance(switch): enhance undefined value
  packages/web-vue/components/switch/switch.vue
Labels: type: enhancement

#2723 fix(Mention): Fix disabled attribute under text-area
  packages/web-vue/components/mention/mention.tsx
Labels: type: 🐞 bug

#2674 feat(calendar): add slots
  packages/web-vue/components/calendar/README.en-US.md
  packages/web-vue/components/calendar/README.zh-CN.md
  packages/web-vue/components/calendar/calendar.tsx
  packages/web-vue/components/calendar/header.tsx
  packages/web-vue/components/calendar/month.tsx
Labels: type: feature request

#2741 feat(watermark): add watermark component
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/watermark/CHANGELOG.md
  packages/web-vue/components/watermark/CHANGELOG.zh-CN.md
  packages/web-vue/components/watermark/README.en-US.md
  packages/web-vue/components/watermark/README.zh-CN.md
  packages/web-vue/components/watermark/TEMPLATE.md
  packages/web-vue/components/watermark/__demo__/basic.md
  packages/web-vue/components/watermark/__demo__/custom.md
  packages/web-vue/components/watermark/__demo__/image.md
  packages/web-vue/components/watermark/__demo__/multiline.md
  packages/web-vue/components/watermark/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/watermark/__test__/demo.test.ts
  packages/web-vue/components/watermark/hooks/use-mutation-observer.ts
  packages/web-vue/components/watermark/index.ts
  packages/web-vue/components/watermark/interface.ts
  packages/web-vue/components/watermark/utils/index.ts
  packages/web-vue/components/watermark/watermark.tsx
Labels: type: feature request
