Repository arco-design/arco-design-vue, pull requests merged in 2024-01, with the labels that each got.

#2914 fix(table): fix span problem
  packages/web-vue/components/table/hooks/use-span.ts
Labels: type: 🐞 bug

#2917 fix(input): fix group style problem
  packages/web-vue/components/input/style/group.less
Labels: type: 🔮 style

#2930 fix(rate): fix not display in nuxt
  packages/web-vue/components/rate/rate.tsx
Labels: type: 🐞 bug

#2925 fix(avatar-group): fix partial avatars not displaying in the avatar group popover
  packages/web-vue/components/avatar/avatar-group.tsx
Labels: type: 🐞 bug

#2924 fix(image): adjust incorrect type definitions and documentation
  packages/web-vue/components/image/README.en-US.md
  packages/web-vue/components/image/README.zh-CN.md
  packages/web-vue/components/image/interface.ts
  packages/web-vue/components/image/preview-group.vue
  packages/web-vue/components/image/preview.vue
  packages/web-vue/components/input/README.en-US.md
  packages/web-vue/components/input/input-password.vue
Labels: type: 🐞 bug

#2916 docs(tree): fix missing event parameters in tree component
  packages/web-vue/components/tree/README.en-US.md
  packages/web-vue/components/tree/README.zh-CN.md
  packages/web-vue/components/tree/tree.vue
Labels: type: docs
