Repository arco-design/arco-design-vue, pull requests merged in 2024-03, with the labels that each got.

#2995 fix(tree): key is a reserved property
  packages/web-vue/components/tree/base-node.vue
Labels: type: 🐞 bug

#2997 fix(collapse): resolve reserved property warning
  packages/web-vue/components/collapse/README.en-US.md
  packages/web-vue/components/collapse/README.zh-CN.md
  packages/web-vue/components/collapse/TEMPLATE.md
  packages/web-vue/components/collapse/collapse-item.tsx
Labels: type: 🐞 bug

#3007 fix(modal): fix fade-modal transition effect works on enter state
  packages/web-vue/components/modal/style/index.less
Labels: type: 🔮 style

#3005 fix(input-number): fix overlap between step button and suffix/append
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-number/style/index.less
Labels: type: 🐞 bug

#3024 feat: add tree slot data
  packages/web-vue/components/tree-select/tree-select.vue
  packages/web-vue/components/tree/base-node.vue
  packages/web-vue/components/tree/tree.vue
Labels: type: feature request

#2958 feat(color-picker): add color-picker component
  packages/arco-vue-docs/locale/en-us.js
  packages/arco-vue-docs/locale/zh-cn.js
  packages/arco-vue-docs/router.ts
  packages/web-vue/components/_utils/color.ts
  packages/web-vue/components/arco-vue.ts
  packages/web-vue/components/color-picker/README.en-US.md
  packages/web-vue/components/color-picker/README.zh-CN.md
  packages/web-vue/components/color-picker/TEMPLATE.md
  packages/web-vue/components/color-picker/__demo__/basic.md
  packages/web-vue/components/color-picker/__demo__/colors.md
  packages/web-vue/components/color-picker/__demo__/disabled.md
  packages/web-vue/components/color-picker/__demo__/format.md
  packages/web-vue/components/color-picker/__demo__/only-panel.md
  packages/web-vue/components/color-picker/__demo__/size.md
  packages/web-vue/components/color-picker/__demo__/trigger-element.md
  packages/web-vue/components/color-picker/__demo__/trigger.md
  packages/web-vue/components/color-picker/__test__/__snapshots__/demo.test.ts.snap
  packages/web-vue/components/color-picker/__test__/demo.test.ts
  packages/web-vue/components/color-picker/__test__/index.test.ts
  packages/web-vue/components/color-picker/color-picker.tsx
  packages/web-vue/components/color-picker/colors.ts
  packages/web-vue/components/color-picker/control-bar.tsx
  packages/web-vue/components/color-picker/hooks/use-control-block.ts
  packages/web-vue/components/color-picker/index.ts
  packages/web-vue/components/color-picker/input-alpha.tsx
  packages/web-vue/components/color-picker/input-hex.tsx
  packages/web-vue/components/color-picker/input-rgb.tsx
  packages/web-vue/components/color-picker/interface.ts
  packages/web-vue/components/color-picker/palette.tsx
  packages/web-vue/components/color-picker/panel.tsx
  packages/web-vue/components/color-picker/style/index.less
  packages/web-vue/components/color-picker/style/index.ts
  packages/web-vue/components/color-picker/style/token.less
  packages/web-vue/components/components.ts
  packages/web-vue/components/index.less
  packages/web-vue/components/index.ts
  packages/web-vue/components/locale/interface.ts
  packages/web-vue/components/locale/lang/ar-eg.ts
  packages/web-vue/components/locale/lang/de-de.ts
  packages/web-vue/components/locale/lang/en-us.ts
  packages/web-vue/components/locale/lang/es-es.ts
  packages/web-vue/components/locale/lang/fr-fr.ts
  packages/web-vue/components/locale/lang/id-id.ts
  packages/web-vue/components/locale/lang/it-it.ts
  packages/web-vue/components/locale/lang/ja-jp.ts
  packages/web-vue/components/locale/lang/km-kh.ts
  packages/web-vue/components/locale/lang/ko-kr.ts
  packages/web-vue/components/locale/lang/ms-my.ts
  packages/web-vue/components/locale/lang/pt-pt.ts
  packages/web-vue/components/locale/lang/th-th.ts
  packages/web-vue/components/locale/lang/vi-vn.ts
  packages/web-vue/components/locale/lang/zh-cn.ts
  packages/web-vue/components/locale/lang/zh-tw.ts
Labels: type: feature request

#3008 fix(tabs): fix transition animation for tab title
  packages/web-vue/components/tabs/style/index.less
Labels: type: 🐞 bug

#3048 fix(empty): fix automatically inherited warn
  packages/web-vue/components/empty/empty.tsx
Labels: type: 🐞 bug

#3045 fix(trigger): fix animation direction for position popup
  packages/web-vue/components/trigger/utils.ts
Labels: type: 🔮 style

#3028 fix(color-picker): 修改错别字
  packages/web-vue/components/locale/lang/zh-cn.ts
Labels: type: 🔮 style

#3037 fix(upload): example code exception
  packages/web-vue/components/upload/__demo__/submit.md
Labels: type: docs

#3030 fix(color-picker): fix v-model not working
  packages/web-vue/components/color-picker/color-picker.tsx
Labels: type: 🐞 bug

#3044 style(tree): fix scrollheight calculation of inline-block element
  packages/web-vue/components/tree/style/index.less
Labels: type: 🔮 style
