Repository arco-design/arco-design-vue, pull requests merged in 2024-10, with the labels that each got.

#3328 fix(locale): correct Khmer translation
  packages/web-vue/components/locale/lang/km-kh.ts
Labels: 🐛 Bug

#3332 fix: fix bug in Rate component doc
  packages/web-vue/components/rate/__demo__/character.md
Labels: 📖 Docs

#3293 feat(button): support autofocus property
  packages/web-vue/components/button/README.en-US.md
  packages/web-vue/components/button/README.zh-CN.md
  packages/web-vue/components/button/button.vue
  packages/web-vue/components/button/interface.ts
Labels: ✨ Feature Request
