Repository arco-design/arco-design-vue, pull requests merged in 2024-09, with the labels that each got.

#3281 fix(calendar): modes prop error
  packages/web-vue/components/calendar/calendar.tsx
Labels: 🐛 Bug

#3268 feat(card): update the types of headerStyle and bodyStyle
  packages/web-vue/components/card/card.tsx
Labels: 📚 Typescript

#3303 feat(textarea): add props textareaAttrs for textarea
  packages/web-vue/components/textarea/README.en-US.md
  packages/web-vue/components/textarea/README.zh-CN.md
  packages/web-vue/components/textarea/textarea.vue
Labels: 💪🏻 Enhancement

#3305 ci: adjust ci run conditions and minor details
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-manager.yml
Labels: ⚙️ CI/CD

#3255 fix(types): update GlobalComponents declarations
  packages/web-vue/components/components.ts
Labels: 📚 Typescript

#3314 fix(input-number): fix readonly not working in button mode
  packages/web-vue/components/input-number/input-number.tsx
  packages/web-vue/components/input-number/style/index.less
Labels: 🐛 Bug
